#image: node:latest 
# version 1
#======================================= =
stages:
    - build
    - storepreprod
    - deployproduction
   
#=======================================
job_build:
    stage: build
    only: 
        - main
    script:
        - cmd.exe /c 'C:\gitlab-runner-TanitWeb\deploy_betovix.bat' #deploy to test server only
        
    tags:
        - TanitWeb

job_storepreprod:
    stage: storepreprod
    only:
        - main
    script:
        - cmd.exe /c 'C:\gitlab-runner-TanitWeb\store_betovix.bat' 
    tags:
        - TanitWeb
 
 #=======================================
#Betovix.com
job_production1:
    stage: deployproduction
    only:  
        - production_betovix
    script:
        - cmd.exe /c 'C:\gitlab-runner-TanitWeb\deploy_website_betovix.bat' 
    tags:
        - AppServer1SportsWeb
job_production2:
    stage: deployproduction
    only:
        - production_betovix
    script:
        - cmd.exe /c 'C:\gitlab-runner-TanitWeb\deploy_website_betovix.bat' 
    tags:
        - AppServer2_SportsWeb 
 #=======================================
#Router
job_production3:
    stage: deployproduction
    only:  
        - production_petekbet
    script:
        - cmd.exe /c 'C:\gitlab-runner-tasks\deploy_website_betovix.bat' 
    tags:
        - PICK777_ROUTER_RUNNER
     
 