#image: node:latest 
# version 1
#======================================= 
stages:
    - build
    - storepreprod
    - deployproduction
   
#=======================================
job_build:
    stage: build
    only: 
        - main
    script:
        - cmd.exe /c 'C:\gitlab-runner-TanitWeb\deploy_fullversion.bat' #deploy to test server only
        
    tags:
        - TanitWeb

job_storepreprod:
    stage: storepreprod
    only:
        - main
    script:
        - cmd.exe /c 'C:\gitlab-runner-TanitWeb\store_fullversion.bat' 
    tags:
        - TanitWeb
#=======================================
#Pick777
job_production3:
    stage: deployproduction
    only:
        - production_pick777
    script:
        - cmd.exe /c 'C:\gitlab-runner-tasks\deploy_website_fullversion.bat' 
    tags:
        - PICK777_ROUTER_RUNNER  
 #=======================================
#Betslip100
job_production4:
    stage: deployproduction
    only:
        - production_betslip100
    script:
        - cmd.exe /c 'C:\gitlab-runner-tasks\deploy_website_fullversion.bat' 
    tags:
        - BETSLIP100_MAFIA_RUNNER  
 #=======================================
#Meda.bet
job_production7:
    stage: deployproduction
    only:  
        - production_medabet
    script:
        - cmd.exe /c 'C:\gitlab-runner-tasks\deploy_website_fullversion.bat' 
    tags:
        - Betovix.com_vm1.2_runner  

     
 