const tournaments = [
    {
        id: 'sr:tournament:17',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:1',
        category: 'England',
        count: 21,
        earliest: '2024-04-21T12:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:34',
        name: 'Ligue 1',
        parentEvent: null,
        seasonName: 'Ligue 1 23/24',
        categoryId: 'sr:category:7',
        category: 'France',
        count: 19,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:35',
        name: 'Bundesliga',
        parentEvent: null,
        seasonName: 'Bundesliga 23/24',
        categoryId: 'sr:category:30',
        category: 'Germany',
        count: 19,
        earliest: '2024-04-21T13:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:23',
        name: 'Serie A',
        parentEvent: null,
        seasonName: 'Serie A 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 25,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:8',
        name: 'LaLiga',
        parentEvent: null,
        seasonName: 'LaLiga 23/24',
        categoryId: 'sr:category:32',
        category: 'Spain',
        count: 14,
        earliest: '2024-04-21T14:15:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:7',
        name: 'UEFA Champions League',
        parentEvent: null,
        seasonName: 'UEFA Champions League 23/24',
        categoryId: 'sr:category:393',
        category: 'International Clubs',
        count: 2,
        earliest: '2024-04-30T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:679',
        name: 'UEFA Europa League',
        parentEvent: null,
        seasonName: 'UEFA Europa League 23/24',
        categoryId: 'sr:category:393',
        category: 'International Clubs',
        count: 2,
        earliest: '2024-05-02T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:34480',
        name: 'UEFA Europa Conference League',
        parentEvent: null,
        seasonName: 'UEFA Europa Conference League 23/24',
        categoryId: 'sr:category:393',
        category: 'International Clubs',
        count: 2,
        earliest: '2024-05-02T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:544',
        name: 'Segunda Federacion',
        parentEvent: null,
        seasonName: 'Segunda Federacion 23/24',
        categoryId: 'sr:category:32',
        category: 'Spain',
        count: 20,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:384',
        name: 'Copa Libertadores',
        parentEvent: null,
        seasonName: 'Copa Libertadores 2024',
        categoryId: 'sr:category:393',
        category: 'International Clubs',
        count: 16,
        earliest: '2024-04-23T22:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:480',
        name: 'Copa Sudamericana',
        parentEvent: null,
        seasonName: 'Copa Sudamericana 2024',
        categoryId: 'sr:category:393',
        category: 'International Clubs',
        count: 16,
        earliest: '2024-04-23T22:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:325',
        name: 'Brasileiro Serie A',
        parentEvent: null,
        seasonName: 'Brasileiro Serie A 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 15,
        earliest: '2024-04-21T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:18',
        name: 'Championship',
        parentEvent: null,
        seasonName: 'Championship 23/24',
        categoryId: 'sr:category:1',
        category: 'England',
        count: 15,
        earliest: '2024-04-22T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:45',
        name: 'Bundesliga',
        parentEvent: null,
        seasonName: 'Bundesliga 23/24',
        categoryId: 'sr:category:17',
        category: 'Austria',
        count: 13,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:703',
        name: 'Primera Nacional',
        parentEvent: null,
        seasonName: 'Primera Nacional 2024',
        categoryId: 'sr:category:48',
        category: 'Argentina',
        count: 13,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1',
        name: 'UEFA Euro',
        parentEvent: null,
        seasonName: 'UEFA Euro 2024',
        categoryId: 'sr:category:4',
        category: 'International',
        count: 12,
        earliest: '2024-06-14T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:24',
        name: 'League One',
        parentEvent: null,
        seasonName: 'League One 23/24',
        categoryId: 'sr:category:1',
        category: 'England',
        count: 12,
        earliest: '2024-04-23T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:30106',
        name: 'Torneo Federal A',
        parentEvent: null,
        seasonName: 'Torneo Federal A 2024',
        categoryId: 'sr:category:48',
        category: 'Argentina',
        count: 11,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:25',
        name: 'League Two',
        parentEvent: null,
        seasonName: 'League Two 23/24',
        categoryId: 'sr:category:1',
        category: 'England',
        count: 11,
        earliest: '2024-04-23T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26556',
        name: 'Serie C, Group B',
        parentEvent: null,
        seasonName: 'Serie C, Group B 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 11,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:182',
        name: 'Ligue 2',
        parentEvent: null,
        seasonName: 'Ligue 2 23/24',
        categoryId: 'sr:category:7',
        category: 'France',
        count: 10,
        earliest: '2024-04-23T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:196',
        name: 'J.League',
        parentEvent: null,
        seasonName: 'J.League 2024',
        categoryId: 'sr:category:52',
        category: 'Japan',
        count: 10,
        earliest: '2024-04-27T04:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:242',
        name: 'MLS',
        parentEvent: null,
        seasonName: 'MLS 2024',
        categoryId: 'sr:category:26',
        category: 'USA',
        count: 10,
        earliest: '2024-04-21T22:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26558',
        name: 'Serie C, Group C',
        parentEvent: null,
        seasonName: 'Serie C, Group C 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 10,
        earliest: '2024-04-21T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:152',
        name: 'Superliga',
        parentEvent: null,
        seasonName: 'Superliga 23/24',
        categoryId: 'sr:category:77',
        category: 'Romania',
        count: 10,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:53',
        name: 'Serie B',
        parentEvent: null,
        seasonName: 'Serie B 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 10,
        earliest: '2024-04-26T18:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27466',
        name: 'Liga MX, Clausura',
        parentEvent: null,
        seasonName: 'Liga MX, Clausura 2024',
        categoryId: 'sr:category:12',
        category: 'Mexico',
        count: 10,
        earliest: '2024-04-22T00:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:172',
        name: '1. Liga',
        parentEvent: null,
        seasonName: '1. Liga 23/24',
        categoryId: 'sr:category:18',
        category: 'Czech Republic',
        count: 9,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:955',
        name: 'Saudi Pro League',
        parentEvent: null,
        seasonName: 'Saudi Pro League 23/24',
        categoryId: 'sr:category:310',
        category: 'Saudi Arabia',
        count: 9,
        earliest: '2024-04-25T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:37',
        name: 'Eredivisie',
        parentEvent: null,
        seasonName: 'Eredivisie 23/24',
        categoryId: 'sr:category:35',
        category: 'Netherlands',
        count: 9,
        earliest: '2024-04-24T16:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:44',
        name: '2. Bundesliga',
        parentEvent: null,
        seasonName: '2. Bundesliga 23/24',
        categoryId: 'sr:category:30',
        category: 'Germany',
        count: 9,
        earliest: '2024-04-26T16:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:229',
        name: 'I Liga',
        parentEvent: null,
        seasonName: 'I Liga 23/24',
        categoryId: 'sr:category:47',
        category: 'Poland',
        count: 8,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:54',
        name: 'LaLiga 2',
        parentEvent: null,
        seasonName: 'LaLiga 2 23/24',
        categoryId: 'sr:category:32',
        category: 'Spain',
        count: 8,
        earliest: '2024-04-21T14:15:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:192',
        name: 'Premier Division',
        parentEvent: null,
        seasonName: 'Premier Division 2024',
        categoryId: 'sr:category:51',
        category: 'Ireland',
        count: 8,
        earliest: '2024-04-22T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:133',
        name: 'Copa America',
        parentEvent: null,
        seasonName: 'Copa America 2024',
        categoryId: 'sr:category:4',
        category: 'International',
        count: 8,
        earliest: '2024-06-21T00:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1339',
        name: 'NB II',
        parentEvent: null,
        seasonName: 'NB II 23/24',
        categoryId: 'sr:category:11',
        category: 'Hungary',
        count: 8,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:135',
        name: '2. Liga',
        parentEvent: null,
        seasonName: '2. Liga 23/24',
        categoryId: 'sr:category:17',
        category: 'Austria',
        count: 8,
        earliest: '2024-04-26T16:10:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:187',
        name: 'NB I',
        parentEvent: null,
        seasonName: 'NB I 23/24',
        categoryId: 'sr:category:11',
        category: 'Hungary',
        count: 8,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:183',
        name: 'National',
        parentEvent: null,
        seasonName: 'National 23/24',
        categoryId: 'sr:category:7',
        category: 'France',
        count: 8,
        earliest: '2024-04-22T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:185',
        name: 'Super League',
        parentEvent: null,
        seasonName: 'Super League 23/24',
        categoryId: 'sr:category:67',
        category: 'Greece',
        count: 8,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:491',
        name: '3. Liga',
        parentEvent: null,
        seasonName: '3. Liga 23/24',
        categoryId: 'sr:category:30',
        category: 'Germany',
        count: 8,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26050',
        name: 'Tercera Federacion, Group 17',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 17 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 8,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:2112',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:532',
        category: 'Nigeria',
        count: 7,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:131',
        name: 'Eerste Divisie',
        parentEvent: null,
        seasonName: 'Eerste Divisie 23/24',
        categoryId: 'sr:category:35',
        category: 'Netherlands',
        count: 7,
        earliest: '2024-04-22T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26042',
        name: 'Tercera Federacion, Group 13',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 13 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 7,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:20',
        name: 'Eliteserien',
        parentEvent: null,
        seasonName: 'Eliteserien 2024',
        categoryId: 'sr:category:5',
        category: 'Norway',
        count: 7,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27070',
        name: 'Primera A, Apertura',
        parentEvent: null,
        seasonName: 'Primera A, Apertura 2024',
        categoryId: 'sr:category:274',
        category: 'Colombia',
        count: 7,
        earliest: '2024-04-21T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1347',
        name: 'Primera B',
        parentEvent: null,
        seasonName: 'Primera B 2024',
        categoryId: 'sr:category:48',
        category: 'Argentina',
        count: 7,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:171',
        name: '1st Division',
        parentEvent: null,
        seasonName: '1st Division 23/24',
        categoryId: 'sr:category:102',
        category: 'Cyprus',
        count: 7,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:808',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:305',
        category: 'Egypt',
        count: 7,
        earliest: '2024-04-22T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:238',
        name: 'Liga Portugal',
        parentEvent: null,
        seasonName: 'Liga Portugal 23/24',
        categoryId: 'sr:category:44',
        category: 'Portugal',
        count: 7,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27398',
        name: 'Liga Nacional. Clausura',
        parentEvent: null,
        seasonName: 'Liga Nacional. Clausura 2024',
        categoryId: 'sr:category:365',
        category: 'Guatemala',
        count: 6,
        earliest: '2024-04-21T21:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:239',
        name: 'Liga Portugal 2',
        parentEvent: null,
        seasonName: 'Liga Portugal 2 23/24',
        categoryId: 'sr:category:44',
        category: 'Portugal',
        count: 6,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:47',
        name: '1. Division',
        parentEvent: null,
        seasonName: '1. Division 23/24',
        categoryId: 'sr:category:8',
        category: 'Denmark',
        count: 6,
        earliest: '2024-04-25T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1335',
        name: 'Copa Colombia',
        parentEvent: null,
        seasonName: 'Copa Colombia 2024',
        categoryId: 'sr:category:274',
        category: 'Colombia',
        count: 6,
        earliest: '2024-04-24T20:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:136',
        name: 'A-League',
        parentEvent: null,
        seasonName: 'A-League 23/24',
        categoryId: 'sr:category:34',
        category: 'Australia',
        count: 6,
        earliest: '2024-04-26T09:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:39',
        name: 'Superliga',
        parentEvent: null,
        seasonName: 'Superliga 23/24',
        categoryId: 'sr:category:8',
        category: 'Denmark',
        count: 6,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:38',
        name: 'Pro League',
        parentEvent: null,
        seasonName: 'Pro League 23/24',
        categoryId: 'sr:category:33',
        category: 'Belgium',
        count: 6,
        earliest: '2024-04-21T16:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:36479',
        name: 'MLS Next Pro',
        parentEvent: null,
        seasonName: 'MLS Next Pro 2024',
        categoryId: 'sr:category:26',
        category: 'USA',
        count: 6,
        earliest: '2024-04-21T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:36',
        name: 'Premiership',
        parentEvent: null,
        seasonName: 'Premiership 23/24',
        categoryId: 'sr:category:22',
        category: 'Scotland',
        count: 6,
        earliest: '2024-04-27T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:34834',
        name: 'Primera Federacion',
        parentEvent: null,
        seasonName: 'Primera Federacion 23/24',
        categoryId: 'sr:category:32',
        category: 'Spain',
        count: 6,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:825',
        name: 'Stars League',
        parentEvent: null,
        seasonName: 'Stars League 23/24',
        categoryId: 'sr:category:353',
        category: 'Qatar',
        count: 6,
        earliest: '2024-04-24T15:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:202',
        name: 'Ekstraklasa',
        parentEvent: null,
        seasonName: 'Ekstraklasa 23/24',
        categoryId: 'sr:category:47',
        category: 'Poland',
        count: 6,
        earliest: '2024-04-21T15:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:2430',
        name: 'AFC U23 Asian Cup',
        parentEvent: null,
        seasonName: 'U23 AFC Asian Cup 2024',
        categoryId: 'sr:category:392',
        category: 'International Youth',
        count: 6,
        earliest: '2024-04-21T15:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:15279',
        name: 'Besta deild, Women',
        parentEvent: null,
        seasonName: 'Besta deild, Women 2024',
        categoryId: 'sr:category:10',
        category: 'Iceland',
        count: 5,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:40',
        name: 'Allsvenskan',
        parentEvent: null,
        seasonName: 'Allsvenskan 2024',
        categoryId: 'sr:category:9',
        category: 'Sweden',
        count: 5,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:206',
        name: 'Championship',
        parentEvent: null,
        seasonName: 'Championship 23/24',
        categoryId: 'sr:category:22',
        category: 'Scotland',
        count: 5,
        earliest: '2024-04-26T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1240',
        name: 'Primera B',
        parentEvent: null,
        seasonName: 'Primera B 2024',
        categoryId: 'sr:category:49',
        category: 'Chile',
        count: 5,
        earliest: '2024-04-21T16:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26174',
        name: 'Primera C',
        parentEvent: null,
        seasonName: 'Primera C 2024',
        categoryId: 'sr:category:48',
        category: 'Argentina',
        count: 5,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:209',
        name: 'League 2',
        parentEvent: null,
        seasonName: 'League 2 23/24',
        categoryId: 'sr:category:22',
        category: 'Scotland',
        count: 5,
        earliest: '2024-04-27T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:52',
        name: 'Super Lig',
        parentEvent: null,
        seasonName: 'Super Lig 23/24',
        categoryId: 'sr:category:46',
        category: 'Turkiye',
        count: 5,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26022',
        name: 'Tercera Federacion, Group 3',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 3 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 5,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:211',
        name: 'Superliga',
        parentEvent: null,
        seasonName: 'Superliga 23/24',
        categoryId: 'sr:category:23',
        category: 'Slovakia',
        count: 5,
        earliest: '2024-04-21T15:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:193',
        name: 'First Division',
        parentEvent: null,
        seasonName: 'First Division 2024',
        categoryId: 'sr:category:51',
        category: 'Ireland',
        count: 5,
        earliest: '2024-04-26T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:218',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:86',
        category: 'Ukraine',
        count: 5,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:200',
        name: 'Premiership',
        parentEvent: null,
        seasonName: 'Premiership 23/24',
        categoryId: 'sr:category:130',
        category: 'Northern Ireland',
        count: 5,
        earliest: '2024-04-22T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1281',
        name: 'Brasileiro Serie C',
        parentEvent: null,
        seasonName: 'Brasileiro Serie C 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 5,
        earliest: '2024-04-21T19:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:216',
        name: 'Challenge League',
        parentEvent: null,
        seasonName: 'Challenge League 23/24',
        categoryId: 'sr:category:25',
        category: 'Switzerland',
        count: 5,
        earliest: '2024-04-22T18:15:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26028',
        name: 'Tercera Federacion, Group 6',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 6 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 4,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1129',
        name: 'Premier League 2',
        parentEvent: null,
        seasonName: 'Premier League 2 23/24',
        categoryId: 'sr:category:252',
        category: 'England Amateur',
        count: 4,
        earliest: '2024-04-22T12:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26018',
        name: 'Tercera Federacion, Group 1',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 1 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 4,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:240',
        name: 'LigaPro Primera A',
        parentEvent: null,
        seasonName: 'LigaPro Primera A 2024',
        categoryId: 'sr:category:165',
        category: 'Ecuador',
        count: 4,
        earliest: '2024-04-27T00:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:205',
        name: 'FNL',
        parentEvent: null,
        seasonName: 'FNL 23/24',
        categoryId: 'sr:category:18',
        category: 'Czech Republic',
        count: 4,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:207',
        name: 'League 1',
        parentEvent: null,
        seasonName: 'League 1 23/24',
        categoryId: 'sr:category:22',
        category: 'Scotland',
        count: 4,
        earliest: '2024-04-27T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:98',
        name: '1. Lig',
        parentEvent: null,
        seasonName: '1. Lig 23/24',
        categoryId: 'sr:category:46',
        category: 'Turkiye',
        count: 4,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:210',
        name: 'Superliga',
        parentEvent: null,
        seasonName: 'Superliga 23/24',
        categoryId: 'sr:category:152',
        category: 'Serbia',
        count: 4,
        earliest: '2024-04-21T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:721',
        name: 'Prva Liga',
        parentEvent: null,
        seasonName: 'Prva Liga 23/24',
        categoryId: 'sr:category:152',
        category: 'Serbia',
        count: 4,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27665',
        name: 'Primera Division',
        parentEvent: null,
        seasonName: 'Primera Division 2024',
        categoryId: 'sr:category:49',
        category: 'Chile',
        count: 4,
        earliest: '2024-04-21T16:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:170',
        name: 'HNL',
        parentEvent: null,
        seasonName: 'HNL 23/24',
        categoryId: 'sr:category:14',
        category: 'Croatia',
        count: 4,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:197',
        name: 'Virsliga',
        parentEvent: null,
        seasonName: 'Virsliga 2024',
        categoryId: 'sr:category:163',
        category: 'Latvia',
        count: 4,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27090',
        name: 'Primera Division, Clausura',
        parentEvent: null,
        seasonName: 'Primera Division, Clausura 2024',
        categoryId: 'sr:category:367',
        category: 'El Salvador',
        count: 4,
        earliest: '2024-04-21T21:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:28955',
        name: 'Liga MX, Women, Clausura',
        parentEvent: null,
        seasonName: 'Liga MX, Women, Clausura 2024',
        categoryId: 'sr:category:12',
        category: 'Mexico',
        count: 4,
        earliest: '2024-04-21T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:186',
        name: 'Super League 2',
        parentEvent: null,
        seasonName: 'Super League 2 23/24',
        categoryId: 'sr:category:67',
        category: 'Greece',
        count: 4,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:971',
        name: 'Arabian Gulf League',
        parentEvent: null,
        seasonName: 'Arabian Gulf League 23/24',
        categoryId: 'sr:category:299',
        category: 'United Arab Emirates',
        count: 4,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:266',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:66',
        category: 'Israel',
        count: 4,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:14758',
        name: 'Campeonato de Portugal',
        parentEvent: null,
        seasonName: 'Campeonato de Portugal 23/24',
        categoryId: 'sr:category:44',
        category: 'Portugal',
        count: 4,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:40731',
        name: 'Divize C',
        parentEvent: null,
        seasonName: 'Divize C 23/24',
        categoryId: 'sr:category:18',
        category: 'Czech Republic',
        count: 4,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:9041',
        name: 'National 3',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:7',
        category: 'France',
        count: 4,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26044',
        name: 'Tercera Federacion, Group 14',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 14 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 4,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:46',
        name: 'Superettan',
        parentEvent: null,
        seasonName: 'Superettan 2024',
        categoryId: 'sr:category:9',
        category: 'Sweden',
        count: 4,
        earliest: '2024-04-22T17:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:19496',
        name: 'Botola Pro D2',
        parentEvent: null,
        seasonName: 'Botola Pro D2 23/24',
        categoryId: 'sr:category:303',
        category: 'Morocco',
        count: 4,
        earliest: '2024-04-21T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1131',
        name: 'Isthmian League, Pr. Div',
        parentEvent: null,
        seasonName: 'Isthmian League, Pr. Div 23/24',
        categoryId: 'sr:category:252',
        category: 'England Amateur',
        count: 4,
        earliest: '2024-04-23T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27094',
        name: 'Primera Division, Clausura',
        parentEvent: null,
        seasonName: 'Primera Division, Clausura 2024',
        categoryId: 'sr:category:289',
        category: 'Costa Rica',
        count: 4,
        earliest: '2024-04-21T23:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26020',
        name: 'Tercera Federacion, Group 2',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 2 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 3,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1111',
        name: 'Northern Premier League, Premier Division',
        parentEvent: null,
        seasonName: 'Northern Premier League, Premier Division 23/24',
        categoryId: 'sr:category:252',
        category: 'England Amateur',
        count: 3,
        earliest: '2024-04-22T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:154',
        name: '1. CFL',
        parentEvent: null,
        seasonName: '1. CFL 23/24',
        categoryId: 'sr:category:386',
        category: 'Montenegro',
        count: 3,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1908',
        name: 'Segunda Division',
        parentEvent: null,
        seasonName: 'Segunda Division 2024',
        categoryId: 'sr:category:57',
        category: 'Uruguay',
        count: 3,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:19238',
        name: 'Division 1',
        parentEvent: null,
        seasonName: 'Division 1 23/24',
        categoryId: 'sr:category:299',
        category: 'United Arab Emirates',
        count: 3,
        earliest: '2024-04-21T13:55:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:2090',
        name: 'Premier League, Women',
        parentEvent: null,
        seasonName: 'Premier League 1, Women 23/24',
        categoryId: 'sr:category:22',
        category: 'Scotland',
        count: 3,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:212',
        name: 'PrvaLiga',
        parentEvent: null,
        seasonName: 'PrvaLiga 23/24',
        categoryId: 'sr:category:24',
        category: 'Slovenia',
        count: 3,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:215',
        name: 'Super League',
        parentEvent: null,
        seasonName: 'Super League 23/24',
        categoryId: 'sr:category:25',
        category: 'Switzerland',
        count: 3,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:24638',
        name: '2nd Division Group 1',
        parentEvent: null,
        seasonName: '2nd Division Group 1 2024',
        categoryId: 'sr:category:5',
        category: 'Norway',
        count: 3,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26036',
        name: 'Tercera Federacion, Group 10',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 10 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 3,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:35791',
        name: 'Gaucho, Serie A2',
        parentEvent: null,
        seasonName: 'Gaucho, Serie A2 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 3,
        earliest: '2024-04-21T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:358',
        name: 'Premiership',
        parentEvent: null,
        seasonName: 'Premiership 23/24',
        categoryId: 'sr:category:322',
        category: 'South Africa',
        count: 3,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:36167',
        name: 'Primera Division, Reserves, Clausura',
        parentEvent: null,
        seasonName: 'Primera Division, Reserves, Clausura 2024',
        categoryId: 'sr:category:367',
        category: 'El Salvador',
        count: 3,
        earliest: '2024-04-21T17:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:390',
        name: 'Brasileiro Serie B',
        parentEvent: null,
        seasonName: 'Brasileiro Serie B 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 3,
        earliest: '2024-04-21T21:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:406',
        name: 'Liga 1',
        parentEvent: null,
        seasonName: 'Liga 1 2024',
        categoryId: 'sr:category:20',
        category: 'Peru',
        count: 3,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:42283',
        name: 'Segunda Division',
        parentEvent: null,
        seasonName: 'Segunda Division 2024',
        categoryId: 'sr:category:49',
        category: 'Chile',
        count: 3,
        earliest: '2024-04-21T16:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:42285',
        name: 'Primera Division, Women',
        parentEvent: null,
        seasonName: 'Primera Division, Women 2024',
        categoryId: 'sr:category:49',
        category: 'Chile',
        count: 3,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:846',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:351',
        category: 'Bahrain',
        count: 3,
        earliest: '2024-04-22T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:937',
        name: 'Botola Pro D1',
        parentEvent: null,
        seasonName: 'Botola Pro D1 23/24',
        categoryId: 'sr:category:303',
        category: 'Morocco',
        count: 3,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:965',
        name: 'Omani League',
        parentEvent: null,
        seasonName: 'Omani League 23/24',
        categoryId: 'sr:category:415',
        category: 'Oman',
        count: 3,
        earliest: '2024-04-22T13:55:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:41',
        name: 'Veikkausliiga',
        parentEvent: null,
        seasonName: 'Veikkausliiga 2024',
        categoryId: 'sr:category:19',
        category: 'Finland',
        count: 2,
        earliest: '2024-04-24T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:410',
        name: 'K-League 1',
        parentEvent: null,
        seasonName: 'K-League 1 2024',
        categoryId: 'sr:category:291',
        category: 'Republic of Korea',
        count: 2,
        earliest: '2024-04-28T05:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26048',
        name: 'Tercera Federacion, Group 16',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 16 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 2,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:254',
        name: 'Cymru Premier',
        parentEvent: null,
        seasonName: 'Cymru Premier 23/24',
        categoryId: 'sr:category:131',
        category: 'Wales',
        count: 2,
        earliest: '2024-04-21T13:15:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:33656',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:914',
        category: 'Ethiopia',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1211',
        name: 'Ligue 1',
        parentEvent: null,
        seasonName: 'Ligue 1 23/24',
        categoryId: 'sr:category:390',
        category: 'Ivory Coast',
        count: 2,
        earliest: '2024-04-21T15:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1191',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:542',
        category: 'Ghana',
        count: 2,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:463',
        name: 'AFC Champions League',
        parentEvent: null,
        seasonName: 'AFC Champions League 23/24',
        categoryId: 'sr:category:393',
        category: 'International Clubs',
        count: 2,
        earliest: '2024-04-23T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26052',
        name: 'Tercera Federacion, Group 18',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 18 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 2,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1117',
        name: 'U21 Pro League',
        parentEvent: null,
        seasonName: 'U21 Pro League 23/24',
        categoryId: 'sr:category:33',
        category: 'Belgium',
        count: 2,
        earliest: '2024-04-22T17:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:247',
        name: 'Parva Liga',
        parentEvent: null,
        seasonName: 'Parva Liga 23/24',
        categoryId: 'sr:category:78',
        category: 'Bulgaria',
        count: 2,
        earliest: '2024-04-21T14:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:498',
        name: 'CONCACAF Champions Cup',
        parentEvent: null,
        seasonName: 'CONCACAF Champions Cup 2024',
        categoryId: 'sr:category:393',
        category: 'International Clubs',
        count: 2,
        earliest: '2024-04-24T02:15:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27765',
        name: 'Liga de Ascenso, Clausura',
        parentEvent: null,
        seasonName: 'Liga de Ascenso, Clausura 2024',
        categoryId: 'sr:category:289',
        category: 'Costa Rica',
        count: 2,
        earliest: '2024-04-21T20:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:278',
        name: 'Primera Division',
        parentEvent: null,
        seasonName: 'Primera Division 2024',
        categoryId: 'sr:category:57',
        category: 'Uruguay',
        count: 2,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:15091',
        name: 'Campeonato Brasileiro, Women',
        parentEvent: null,
        seasonName: 'Brasileiro A1, Women 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 2,
        earliest: '2024-04-21T13:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:532',
        name: '2. Liga',
        parentEvent: null,
        seasonName: '2. Liga 23/24',
        categoryId: 'sr:category:24',
        category: 'Slovenia',
        count: 2,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1103',
        name: 'Oberliga Niederrhein',
        parentEvent: null,
        seasonName: 'Oberliga Niederrhein 23/24',
        categoryId: 'sr:category:122',
        category: 'Germany Amateur',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26034',
        name: 'Tercera Federacion, Group 9',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 9 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 2,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:55',
        name: 'Ykkosliiga',
        parentEvent: null,
        seasonName: 'Ykkonen 2024',
        categoryId: 'sr:category:19',
        category: 'Finland',
        count: 2,
        earliest: '2024-04-24T15:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26026',
        name: 'Tercera Federacion, Group 5',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 5 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 2,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:146',
        name: 'Oberliga Westfalen',
        parentEvent: null,
        seasonName: 'Oberliga Westfalen 23/24',
        categoryId: 'sr:category:122',
        category: 'Germany Amateur',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1894',
        name: 'A-League, Women',
        parentEvent: null,
        seasonName: 'A-League, Women 23/24',
        categoryId: 'sr:category:34',
        category: 'Australia',
        count: 2,
        earliest: '2024-04-27T05:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:649',
        name: 'Chinese Super League',
        parentEvent: null,
        seasonName: 'Chinese Super League 2024',
        categoryId: 'sr:category:99',
        category: 'China',
        count: 2,
        earliest: '2024-04-26T11:35:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:67',
        name: 'Ettan, Norra',
        parentEvent: null,
        seasonName: 'Ettan, Norra 2024',
        categoryId: 'sr:category:9',
        category: 'Sweden',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:671',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:296',
        category: 'Armenia',
        count: 2,
        earliest: '2024-04-22T11:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:673',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 2024',
        categoryId: 'sr:category:201',
        category: 'Faroe Islands',
        count: 2,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:36281',
        name: 'Liga Femenina',
        parentEvent: null,
        seasonName: 'Liga Femenina 2024',
        categoryId: 'sr:category:274',
        category: 'Colombia',
        count: 2,
        earliest: '2024-04-21T21:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:14151',
        name: 'CFL',
        parentEvent: null,
        seasonName: 'CFL 23/24',
        categoryId: 'sr:category:18',
        category: 'Czech Republic',
        count: 2,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:68',
        name: 'Ettan, Sodra',
        parentEvent: null,
        seasonName: 'Ettan, Sodra 2024',
        categoryId: 'sr:category:9',
        category: 'Sweden',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26038',
        name: 'Tercera Federacion, Group 11',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 11 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 2,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:690',
        name: 'Division Nationale',
        parentEvent: null,
        seasonName: 'Division Nationale 23/24',
        categoryId: 'sr:category:197',
        category: 'Luxembourg',
        count: 2,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:696',
        name: 'UEFA Champions League Women',
        parentEvent: null,
        seasonName: 'UEFA Champions League Women 23/24',
        categoryId: 'sr:category:393',
        category: 'International Clubs',
        count: 2,
        earliest: '2024-04-27T16:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1015',
        name: 'Liga 1',
        parentEvent: null,
        seasonName: 'Liga 1 23/24',
        categoryId: 'sr:category:368',
        category: 'Indonesia',
        count: 2,
        earliest: '2024-04-22T08:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:19492',
        name: '2. Division A',
        parentEvent: null,
        seasonName: '2. Division A 23/24',
        categoryId: 'sr:category:305',
        category: 'Egypt',
        count: 2,
        earliest: '2024-04-21T13:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1388',
        name: 'Serie D, Girone H',
        parentEvent: null,
        seasonName: 'Serie D, Girone H 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1690',
        name: 'National Womens Soccer League',
        parentEvent: null,
        seasonName: 'National Womens Soccer League 2024',
        categoryId: 'sr:category:26',
        category: 'USA',
        count: 2,
        earliest: '2024-04-21T22:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:24646',
        name: '3rd Division Group 3',
        parentEvent: null,
        seasonName: '3rd Division Group 3 2024',
        categoryId: 'sr:category:5',
        category: 'Norway',
        count: 2,
        earliest: '2024-04-22T17:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1384',
        name: 'Serie D, Girone F',
        parentEvent: null,
        seasonName: 'Serie D, Girone F 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:29842',
        name: 'Professional Development League',
        parentEvent: null,
        seasonName: 'Professional Development League 23/24',
        categoryId: 'sr:category:252',
        category: 'England Amateur',
        count: 2,
        earliest: '2024-04-22T12:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1376',
        name: 'Serie D, Girone B',
        parentEvent: null,
        seasonName: 'Serie D, Girone B 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:188',
        name: 'Besta deild',
        parentEvent: null,
        seasonName: 'Besta deild 2024',
        categoryId: 'sr:category:10',
        category: 'Iceland',
        count: 2,
        earliest: '2024-04-21T17:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:20162',
        name: 'Rwanda Premier League',
        parentEvent: null,
        seasonName: 'Rwanda Premier League 23/24',
        categoryId: 'sr:category:951',
        category: 'Rwanda',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:232',
        name: 'Women Bundesliga',
        parentEvent: null,
        seasonName: 'Women Bundesliga 23/24',
        categoryId: 'sr:category:122',
        category: 'Germany Amateur',
        count: 2,
        earliest: '2024-04-21T16:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:32039',
        name: 'Brasileiro Serie A2, Women',
        parentEvent: null,
        seasonName: 'Brasileiro Serie A2, Women 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 2,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:23479',
        name: 'Premier Soccer League',
        parentEvent: null,
        seasonName: 'Premier Soccer League 2024',
        categoryId: 'sr:category:815',
        category: 'Zimbabwe',
        count: 2,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26046',
        name: 'Tercera Federacion, Group 15',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 15 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 2,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27098',
        name: 'Division de Honor, Apertura',
        parentEvent: null,
        seasonName: 'Division de Honor, Apertura 2024',
        categoryId: 'sr:category:280',
        category: 'Paraguay',
        count: 2,
        earliest: '2024-04-21T21:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:2298',
        name: 'Division 1',
        parentEvent: null,
        seasonName: 'Division 1 23/24',
        categoryId: 'sr:category:310',
        category: 'Saudi Arabia',
        count: 2,
        earliest: '2024-04-22T16:10:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:40533',
        name: 'Liga Premier Serie A',
        parentEvent: null,
        seasonName: 'Liga Premier Serie A 23/24',
        categoryId: 'sr:category:12',
        category: 'Mexico',
        count: 2,
        earliest: '2024-04-21T22:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27102',
        name: 'Liga Panamena de Futbol, Apertura',
        parentEvent: null,
        seasonName: 'Liga Panamena de Futbol, Apertura 2024',
        categoryId: 'sr:category:526',
        category: 'Panama',
        count: 2,
        earliest: '2024-04-21T21:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:328',
        name: 'Coppa Italia',
        parentEvent: null,
        seasonName: 'Coppa Italia 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 2,
        earliest: '2024-04-23T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1254',
        name: 'Segunda Division',
        parentEvent: null,
        seasonName: 'Segunda Division 2024',
        categoryId: 'sr:category:280',
        category: 'Paraguay',
        count: 2,
        earliest: '2024-04-21T13:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:40817',
        name: 'Ligue 1',
        parentEvent: null,
        seasonName: 'Ligue 1 23/24',
        categoryId: 'sr:category:832',
        category: 'Mali',
        count: 2,
        earliest: '2024-04-21T16:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:777',
        name: 'K-League 2',
        parentEvent: null,
        seasonName: 'K-League 2 2024',
        categoryId: 'sr:category:291',
        category: 'Republic of Korea',
        count: 2,
        earliest: '2024-04-27T07:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:11352',
        name: 'Krajsky prebor',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:18',
        category: 'Czech Republic',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1238',
        name: 'Primera B',
        parentEvent: null,
        seasonName: 'Primera B 2024',
        categoryId: 'sr:category:274',
        category: 'Colombia',
        count: 1,
        earliest: '2024-04-21T20:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1127',
        name: 'Primera Division Women',
        parentEvent: null,
        seasonName: 'Primera Division Women 23/24',
        categoryId: 'sr:category:32',
        category: 'Spain',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1115',
        name: 'CAF Confederations Cup',
        parentEvent: null,
        seasonName: 'CAF Confederations Cup 23/24',
        categoryId: 'sr:category:393',
        category: 'International Clubs',
        count: 1,
        earliest: '2024-04-21T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:515',
        name: 'II Liga',
        parentEvent: null,
        seasonName: 'II Liga 23/24',
        categoryId: 'sr:category:47',
        category: 'Poland',
        count: 1,
        earliest: '2024-04-22T16:15:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1109',
        name: 'Oberliga Rheinland-Pfalz',
        parentEvent: null,
        seasonName: 'Oberliga Rheinland-Pfalz 23/24',
        categoryId: 'sr:category:122',
        category: 'Germany Amateur',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1105',
        name: 'Oberliga Mittelrhein',
        parentEvent: null,
        seasonName: 'Oberliga Mittelrhein 23/24',
        categoryId: 'sr:category:122',
        category: 'Germany Amateur',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1101',
        name: 'Promotion League',
        parentEvent: null,
        seasonName: 'Promotion League 23/24',
        categoryId: 'sr:category:25',
        category: 'Switzerland',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:562',
        name: 'Liga 2',
        parentEvent: null,
        seasonName: 'Liga 2 23/24',
        categoryId: 'sr:category:77',
        category: 'Romania',
        count: 1,
        earliest: '2024-04-24T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:629',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:134',
        category: 'Malta',
        count: 1,
        earliest: '2024-04-21T14:15:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:630',
        name: 'Challenge League',
        parentEvent: null,
        seasonName: 'Challenge League 23/24',
        categoryId: 'sr:category:134',
        category: 'Malta',
        count: 1,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:677',
        name: '1.Liga',
        parentEvent: null,
        seasonName: '1.Liga 2024',
        categoryId: 'sr:category:163',
        category: 'Latvia',
        count: 1,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1044',
        name: "The FA Women's Super League",
        parentEvent: null,
        seasonName: "The FA Women's Super League 23/24",
        categoryId: 'sr:category:252',
        category: 'England Amateur',
        count: 1,
        earliest: '2024-04-21T13:15:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:685',
        name: 'Super Liga',
        parentEvent: null,
        seasonName: 'Super Liga 23/24',
        categoryId: 'sr:category:279',
        category: 'Moldova',
        count: 1,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:70',
        name: 'Division 2, Norra Svealand',
        parentEvent: null,
        seasonName: 'Division 2, Norra Svealand 2024',
        categoryId: 'sr:category:9',
        category: 'Sweden',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:9856',
        name: 'Division de Honor Juvenil - Grupo I',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:32',
        category: 'Spain',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:704',
        name: 'Erovnuli Liga',
        parentEvent: null,
        seasonName: 'Erovnuli Liga 2024',
        categoryId: 'sr:category:270',
        category: 'Georgia',
        count: 1,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:72',
        name: 'Division 2, Sodra Gotaland',
        parentEvent: null,
        seasonName: 'Division 2, Sodra Gotaland 2024',
        categoryId: 'sr:category:9',
        category: 'Sweden',
        count: 1,
        earliest: '2024-04-22T17:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:92749',
        name: 'First Division League',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:803',
        category: 'Tanzania',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:73',
        name: 'Division 2, Vastra Gotaland',
        parentEvent: null,
        seasonName: 'Division 2, Vastra Gotaland 2024',
        categoryId: 'sr:category:9',
        category: 'Sweden',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:742',
        name: 'Primera Divisio',
        parentEvent: null,
        seasonName: 'Primera Divisio 23/24',
        categoryId: 'sr:category:376',
        category: 'Andorra',
        count: 1,
        earliest: '2024-04-21T16:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:76',
        name: 'DBU Pokalen',
        parentEvent: null,
        seasonName: 'DBU Pokalen 23/24',
        categoryId: 'sr:category:8',
        category: 'Denmark',
        count: 1,
        earliest: '2024-05-09T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:2340',
        name: 'Campionato Primavera 1',
        parentEvent: null,
        seasonName: 'Campionato Primavera 1 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 1,
        earliest: '2024-04-22T09:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:23551',
        name: 'Azadegan League',
        parentEvent: null,
        seasonName: 'Azadegan League 23/24',
        categoryId: 'sr:category:301',
        category: 'Iran',
        count: 1,
        earliest: '2024-04-21T14:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:231',
        name: 'Primera Division',
        parentEvent: null,
        seasonName: 'Primera Division 2024',
        categoryId: 'sr:category:281',
        category: 'Venezuela',
        count: 1,
        earliest: '2024-04-21T21:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:22',
        name: '1st Division',
        parentEvent: null,
        seasonName: '1st Division 2024',
        categoryId: 'sr:category:5',
        category: 'Norway',
        count: 1,
        earliest: '2024-04-27T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:217',
        name: 'DFB Pokal',
        parentEvent: null,
        seasonName: 'DFB Pokal 23/24',
        categoryId: 'sr:category:30',
        category: 'Germany',
        count: 1,
        earliest: '2024-05-25T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:2142',
        name: 'Super League',
        parentEvent: null,
        seasonName: 'Super League 23/24',
        categoryId: 'sr:category:812',
        category: 'Zambia',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:214',
        name: 'Damallsvenskan',
        parentEvent: null,
        seasonName: 'Damallsvenskan 2024',
        categoryId: 'sr:category:9',
        category: 'Sweden',
        count: 1,
        earliest: '2024-04-22T17:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:2436',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:803',
        category: 'Tanzania',
        count: 1,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:709',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:297',
        category: 'Azerbaijan',
        count: 1,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:24648',
        name: '3rd Division Group 4',
        parentEvent: null,
        seasonName: '3rd Division Group 4 2024',
        categoryId: 'sr:category:5',
        category: 'Norway',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:20808',
        name: 'Serie A, Women',
        parentEvent: null,
        seasonName: 'Serie A, Women 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:25839',
        name: 'III Liga, Group 3',
        parentEvent: null,
        seasonName: 'III Liga, Group 3 23/24',
        categoryId: 'sr:category:47',
        category: 'Poland',
        count: 1,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:104146',
        name: 'Tercera Federacion, Women',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:32',
        category: 'Spain',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:199',
        name: '1. MFL',
        parentEvent: null,
        seasonName: '1. MFL 23/24',
        categoryId: 'sr:category:159',
        category: 'North Macedonia',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:198',
        name: 'A Lyga',
        parentEvent: null,
        seasonName: 'A Lyga 2024',
        categoryId: 'sr:category:160',
        category: 'Lithuania',
        count: 1,
        earliest: '2024-04-21T15:25:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26030',
        name: 'Tercera Federacion, Group 7',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 7 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 1,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26032',
        name: 'Tercera Federacion, Group 8',
        parentEvent: null,
        seasonName: 'Tercera Federacion, Group 8 23/24',
        categoryId: 'sr:category:421',
        category: 'Spain Amateur',
        count: 1,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:43359',
        name: 'Srpska Liga, Istok',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:152',
        category: 'Serbia',
        count: 1,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:19276',
        name: 'Cup, Women',
        parentEvent: null,
        seasonName: 'Cup, Women 2024',
        categoryId: 'sr:category:10',
        category: 'Iceland',
        count: 1,
        earliest: '2024-04-22T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:19242',
        name: 'Primera Division',
        parentEvent: null,
        seasonName: 'Primera Division 23/24',
        categoryId: 'sr:category:389',
        category: 'Nicaragua',
        count: 1,
        earliest: '2024-04-22T01:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26058',
        name: 'Southern League Premier South',
        parentEvent: null,
        seasonName: 'Southern League Premier South 23/24',
        categoryId: 'sr:category:252',
        category: 'England Amateur',
        count: 1,
        earliest: '2024-04-22T18:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1906',
        name: 'Championship',
        parentEvent: null,
        seasonName: 'Championship 23/24',
        categoryId: 'sr:category:322',
        category: 'South Africa',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:19',
        name: 'FA Cup',
        parentEvent: null,
        seasonName: 'FA Cup 23/24',
        categoryId: 'sr:category:1',
        category: 'England',
        count: 1,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1892',
        name: 'Premier League',
        parentEvent: null,
        seasonName: 'Premier League 23/24',
        categoryId: 'sr:category:502',
        category: 'Jamaica',
        count: 1,
        earliest: '2024-04-23T00:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:26974',
        name: 'Iraqi League',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:490',
        category: 'Iraq',
        count: 1,
        earliest: '2024-04-21T12:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:18464',
        name: 'Primera Division, Women',
        parentEvent: null,
        seasonName: 'Primera Division, Women 2024',
        categoryId: 'sr:category:48',
        category: 'Argentina',
        count: 1,
        earliest: '2024-04-21T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:184',
        name: 'Hessenliga',
        parentEvent: null,
        seasonName: 'Hessenliga 23/24',
        categoryId: 'sr:category:122',
        category: 'Germany Amateur',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:18350',
        name: 'Championship, Women',
        parentEvent: null,
        seasonName: 'Championship, Women 23/24',
        categoryId: 'sr:category:252',
        category: 'England Amateur',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27416',
        name: 'Liga Nacional. Clausura',
        parentEvent: null,
        seasonName: 'Liga Nacional. Clausura 2024',
        categoryId: 'sr:category:437',
        category: 'Honduras',
        count: 1,
        earliest: '2024-04-21T23:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:179',
        name: 'Kakkonen, Group A',
        parentEvent: null,
        seasonName: 'Kakkonen, Group A 2024',
        categoryId: 'sr:category:19',
        category: 'Finland',
        count: 1,
        earliest: '2024-04-21T15:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:173',
        name: 'National League',
        parentEvent: null,
        seasonName: 'National League 23/24',
        categoryId: 'sr:category:1',
        category: 'England',
        count: 1,
        earliest: '2024-04-24T18:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:27811',
        name: 'Sul-Mato-Grossense',
        parentEvent: null,
        seasonName: 'Sul-Mato-Grossense 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 1,
        earliest: '2024-04-21T19:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:28165',
        name: 'USL League One',
        parentEvent: null,
        seasonName: 'USL League One 2024',
        categoryId: 'sr:category:26',
        category: 'USA',
        count: 1,
        earliest: '2024-04-21T23:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:282',
        name: 'Cup',
        parentEvent: null,
        seasonName: 'Cup 23/24',
        categoryId: 'sr:category:18',
        category: 'Czech Republic',
        count: 1,
        earliest: '2024-04-24T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:28432',
        name: 'Canadian Premier League',
        parentEvent: null,
        seasonName: 'Canadian Premier League 2024',
        categoryId: 'sr:category:388',
        category: 'Canada',
        count: 1,
        earliest: '2024-04-21T20:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:28538',
        name: 'Copa de la Liga',
        parentEvent: null,
        seasonName: 'Copa de la Liga 2024',
        categoryId: 'sr:category:48',
        category: 'Argentina',
        count: 1,
        earliest: '2024-04-21T18:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:169',
        name: 'Vysshaya Liga',
        parentEvent: null,
        seasonName: 'Vysshaya Liga 2024',
        categoryId: 'sr:category:91',
        category: 'Belarus',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:31833',
        name: 'Campeonato Rondoniense',
        parentEvent: null,
        seasonName: 'Campeonato Rondoniense 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 1,
        earliest: '2024-04-21T19:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:32367',
        name: 'Victoria Premier League 1',
        parentEvent: null,
        seasonName: 'Victoria Premier League 1 2024',
        categoryId: 'sr:category:34',
        category: 'Australia',
        count: 1,
        earliest: '2024-04-22T10:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1682',
        name: 'Tunisian Cup',
        parentEvent: null,
        seasonName: 'Tunisian Cup 2024',
        categoryId: 'sr:category:378',
        category: 'Tunisia',
        count: 1,
        earliest: '2024-04-21T13:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:326',
        name: 'Beker van Belgie',
        parentEvent: null,
        seasonName: 'Beker van Belgie 23/24',
        categoryId: 'sr:category:33',
        category: 'Belgium',
        count: 1,
        earliest: '2024-05-09T13:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:330',
        name: 'KNVB beker',
        parentEvent: null,
        seasonName: 'KNVB beker 23/24',
        categoryId: 'sr:category:35',
        category: 'Netherlands',
        count: 1,
        earliest: '2024-04-21T16:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:335',
        name: 'Coupe de France',
        parentEvent: null,
        seasonName: 'Coupe de France 23/24',
        categoryId: 'sr:category:7',
        category: 'France',
        count: 1,
        earliest: '2024-05-25T17:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:168',
        name: 'Regionalliga Centre',
        parentEvent: null,
        seasonName: 'Regionalliga Centre 23/24',
        categoryId: 'sr:category:97',
        category: 'Austria Amateur',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1614',
        name: 'Paulista, Serie A3',
        parentEvent: null,
        seasonName: 'Paulista, Serie A3 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:347',
        name: 'Scottish Cup',
        parentEvent: null,
        seasonName: 'Scottish Cup 23/24',
        categoryId: 'sr:category:22',
        category: 'Scotland',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1596',
        name: 'Copa do Nordeste',
        parentEvent: null,
        seasonName: 'Copa do Nordeste 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 1,
        earliest: '2024-04-21T22:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:80',
        name: 'Svenska Cup',
        parentEvent: null,
        seasonName: 'Svenska Cup 23/24',
        categoryId: 'sr:category:9',
        category: 'Sweden',
        count: 1,
        earliest: '2024-05-01T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:33611',
        name: 'Big League',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:824',
        category: 'Uganda',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:23097',
        name: 'U19 League, Women',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:7',
        category: 'France',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:365',
        name: 'Bulgarian Cup',
        parentEvent: null,
        seasonName: 'Bulgarian Cup 23/24',
        categoryId: 'sr:category:78',
        category: 'Bulgaria',
        count: 1,
        earliest: '2024-04-24T15:45:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:36667',
        name: 'Cearense, Serie B',
        parentEvent: null,
        seasonName: 'Cearense, Serie B 2024',
        categoryId: 'sr:category:13',
        category: 'Brazil',
        count: 1,
        earliest: '2024-04-21T20:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:37635',
        name: 'Ligue A',
        parentEvent: null,
        seasonName: 'Ligue A 23/24',
        categoryId: 'sr:category:956',
        category: 'Burundi',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1380',
        name: 'Serie D, Girone D',
        parentEvent: null,
        seasonName: 'Serie D, Girone D 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:107660',
        name: 'Campeonato Nacional II, Women',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:44',
        category: 'Portugal',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:39173',
        name: 'Segunda Division',
        parentEvent: null,
        seasonName: 'Segunda Division 23/24',
        categoryId: 'sr:category:367',
        category: 'El Salvador',
        count: 1,
        earliest: '2024-04-21T17:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:1374',
        name: 'Serie D, Girone A',
        parentEvent: null,
        seasonName: 'Serie D, Girone A 23/24',
        categoryId: 'sr:category:31',
        category: 'Italy',
        count: 1,
        earliest: '2024-04-21T13:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:40387',
        name: 'U23 Liga MX',
        parentEvent: null,
        seasonName: 'U23 Liga MX, Apertura 2024',
        categoryId: 'sr:category:12',
        category: 'Mexico',
        count: 1,
        earliest: '2024-04-21T15:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:40471',
        name: '3. Liga, West',
        parentEvent: null,
        seasonName: '3. Liga, West 23/24',
        categoryId: 'sr:category:23',
        category: 'Slovakia',
        count: 1,
        earliest: '2024-04-21T14:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:915',
        name: 'Pro League',
        parentEvent: null,
        seasonName: 'Pro League 23/24',
        categoryId: 'sr:category:301',
        category: 'Iran',
        count: 1,
        earliest: '2024-04-21T13:30:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:tournament:40727',
        name: 'Divize A',
        parentEvent: null,
        seasonName: 'Divize A 23/24',
        categoryId: 'sr:category:18',
        category: 'Czech Republic',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
    {
        id: 'sr:simple_tournament:11144',
        name: 'A Lyga, Women',
        parentEvent: null,
        seasonName: null,
        categoryId: 'sr:category:160',
        category: 'Lithuania',
        count: 1,
        earliest: '2024-04-21T14:00:00.000Z',
        sportId: 'sr:sport:1',
    },
];

export default tournaments;
