const home = [
    {
        section: 'recommended',
        games: [
            {
                id: '75d9ec83-4aba-4c28-86f3-3ac34657cf64',
                slug: 'pragmatic-play-sweet-bonanza',
                identifier: 'pragmaticexternal:SweetBonanza',
                featureGroup: 'pragmaticexternal_basic_lv',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Sweet Bonanza',
                description: null,
                category: 'slots',
                theme: 'fruits',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.965,
                hitRate: null,
                lines: 20,
                ways: null,
                multiplier: 21175,
                volatility: 'high',
                releasedAt: '2019-06-28T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2024-04-08T20:31:13.924Z',
            },
            {
                id: 'b57e848f-611a-44f6-a6c4-564357e292f2',
                slug: 'hacksaw-wanted-dead-or-a-wild',
                identifier: 'relax:WantedDeadoraWild',
                featureGroup: 'relax_hacksaw_basic',
                type: 'softswiss',
                provider: 'relax',
                producer: 'hacksaw',
                title: 'Wanted Dead or a Wild',
                description:
                    'Step into our rough Western themed game filled with merciless outlaws, deadly duels and legendary robberies. Wanted Dead or a Wild is an action packed 5 x 5 grid slot featuring a max win of up to 12,500x!',
                category: 'slots',
                theme: 'western',
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9638,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: 12500,
                volatility: 'high',
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2024-04-08T13:44:48.307Z',
            },
            {
                id: 'afec0708-dc46-469a-a5a6-e976fea0da51',
                slug: 'pragmatic-play-sugar-rush-1000',
                identifier: 'pragmaticexternal:SugarRush1000',
                featureGroup: 'pragmaticexternal_basic',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Sugar Rush 1000',
                description: null,
                category: 'slots',
                theme: 'sweets',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9653,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: 25000,
                volatility: 'very-high',
                releasedAt: '2024-03-18T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2024-03-11T11:20:59.762Z',
                updatedAt: '2024-03-29T17:42:20.609Z',
            },
            {
                id: '1fd227bd-22b4-4f33-997f-56bf3ac2eac7',
                slug: 'pragmatic-play-gates-of-olympus-1000',
                identifier: 'pragmaticexternal:GatesofOlympus1000',
                featureGroup: 'pragmaticexternal_basic',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Gates of Olympus 1000',
                description: null,
                category: 'slots',
                theme: 'ancient_civilizations',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.965,
                hitRate: null,
                lines: 20,
                ways: null,
                multiplier: 15000,
                volatility: 'high',
                releasedAt: '2023-12-14T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-12-04T08:27:31.386Z',
                updatedAt: '2023-12-14T09:01:43.049Z',
            },
            {
                id: 'c20225c9-3cc8-4f4c-b799-621382133685',
                slug: 'evolution-crazy-time',
                identifier: 'evolution:crazytime',
                featureGroup: 'evolution_lightning',
                type: 'softswiss',
                provider: 'evolution',
                producer: 'evolution',
                title: 'Crazy Time',
                description:
                    'Crazy Time is a unique live online game show built on our extremely successful Dream Catcher money wheel concept. Now the interactive fun and excitement reaches crazy new levels with the chance to add multipliers from the Top Slot in each game round and in four exciting bonus games. Interactive elements and advanced technology make it possible for players to win different multipliers in two out of the four bonus games. Offering live entertainment with added advanced RNG gameplay, Crazy Time offers a one-of-a-kind player experience',
                category: 'lottery',
                theme: 'other',
                hasFreespins: false,
                hasLive: true,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.955,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: 15,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['live', 'game-show'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2024-04-02T10:22:22.144Z',
            },
            {
                id: '685108a8-4579-4816-9b95-2d755b24e17f',
                slug: 'evolution-duelbits-first-person-blackjack',
                identifier: 'evolution:DuelbitsFirstPersonBlackjack',
                featureGroup: 'evolution_live_duelbits',
                type: 'softswiss',
                provider: 'evolution',
                producer: 'evolution',
                title: 'Duelbits First Person Blackjack',
                description: null,
                category: 'card',
                theme: 'other',
                hasFreespins: false,
                hasLive: true,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.9929,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['live', 'blackjack'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2024-03-12T16:54:35.212Z',
            },
            {
                id: '53f2dd21-7d32-4bfc-95a8-2a63f94cbdd8',
                slug: 'pragmatic-play-gates-of-olympus',
                identifier: 'pragmaticexternal:GatesOfOlympus1',
                featureGroup: 'pragmaticexternal_basic_lv',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Gates of Olympus',
                description: null,
                category: 'slots',
                theme: 'ancient_civilizations',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.965,
                hitRate: null,
                lines: 20,
                ways: null,
                multiplier: 5000,
                volatility: 'very-high',
                releasedAt: '2021-02-25T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2024-03-29T17:42:24.351Z',
            },
            {
                id: '78b9c5d0-7313-412b-9ee8-de5322c14117',
                slug: 'hacksaw-le-bandit',
                identifier: 'relax:LeBandit96',
                featureGroup: 'relax_hacksaw_basic',
                type: 'softswiss',
                provider: 'relax',
                producer: 'hacksaw',
                title: 'Le Bandit',
                description: null,
                category: 'slots',
                theme: 'st_patrick_day',
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9634,
                hitRate: 0.3247,
                lines: null,
                ways: null,
                multiplier: 10000,
                volatility: 'medium-high',
                releasedAt: '2023-08-24T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2023-09-30T15:31:39.569Z',
            },
            {
                id: '656c74e0-a721-4b89-b6b5-4ae9c0dc9980',
                slug: 'evolution-duelbits-blackjack',
                identifier: 'evolution:DuelbitsBlackjack',
                featureGroup: 'evolution_live_duelbits',
                type: 'softswiss',
                provider: 'evolution',
                producer: 'evolution',
                title: 'Duelbits Blackjack',
                description: null,
                category: 'card',
                theme: 'other',
                hasFreespins: false,
                hasLive: true,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.9929,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['live', 'blackjack'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2024-04-11T12:22:26.000Z',
            },
            {
                id: '3d6b2cb6-3b16-4b97-bf40-4e61e4d9a292',
                slug: 'push-gaming-retro-tapes',
                identifier: 'pushgaming:retrotapes-01',
                featureGroup: 'pushgaming_basic_lv',
                type: 'softswiss',
                provider: 'pushgaming',
                producer: 'pushgaming',
                title: 'Retro Tapes',
                description: null,
                category: 'slots',
                theme: 'retro',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9647,
                hitRate: null,
                lines: 5,
                ways: null,
                multiplier: 10000,
                volatility: 'high',
                releasedAt: '2022-11-23T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2024-03-29T17:42:27.702Z',
            },
            {
                id: '5f4ffb19-955e-4f2c-9227-b2669898ec7a',
                slug: 'pragmatic-play-fruit-party',
                identifier: 'pragmaticexternal:FruitParty1',
                featureGroup: 'pragmaticexternal_basic_lv',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Fruit Party',
                description: null,
                category: 'slots',
                theme: 'fruits',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.965,
                hitRate: null,
                lines: 20,
                ways: null,
                multiplier: 5000,
                volatility: 'high',
                releasedAt: '2020-05-28T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2023-09-30T15:31:39.569Z',
            },
            {
                id: 'fd831cf6-e0a0-4dc8-9b0f-b56b26cca75f',
                slug: 'pragmatic-play-big-bass-secrets-of-the-golden-lake',
                identifier: 'pragmaticexternal:BigBassSecretsoftheGoldenLake',
                featureGroup: 'pragmaticexternal_basic',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Big Bass Secrets of the Golden Lake',
                description: null,
                category: 'slots',
                theme: 'underwater_world',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9607,
                hitRate: null,
                lines: 10,
                ways: null,
                multiplier: 5000,
                volatility: 'very-high',
                releasedAt: '2024-04-08T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2024-04-01T10:25:43.770Z',
                updatedAt: '2024-04-09T09:41:00.614Z',
            },
            {
                id: '3a1ec6ae-4b22-48f1-ad1c-f60eb7984361',
                slug: 'hacksaw-cash-crew',
                identifier: 'relax:CashCrew96',
                featureGroup: 'relax_hacksaw_basic',
                type: 'softswiss',
                provider: 'relax',
                producer: 'hacksaw',
                title: 'Cash Crew',
                description: null,
                category: 'slots',
                theme: 'other',
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9626,
                hitRate: 0.318,
                lines: 19,
                ways: null,
                multiplier: 10000,
                volatility: 'medium-high',
                releasedAt: '2024-04-04T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2024-03-25T19:18:10.789Z',
                updatedAt: '2024-04-04T08:49:50.308Z',
            },
            {
                id: '1142c2d7-5512-4c8b-8da6-b554cafe313c',
                slug: 'evolution-roulette-live',
                identifier: 'evolution:roulette_direct',
                featureGroup: 'evolution_live',
                type: 'softswiss',
                provider: 'evolution',
                producer: 'evolution',
                title: 'Roulette Live',
                description: 'Evolution Live Roulette is the most popular authentic and exciting live dealer Roulette available online. ',
                category: 'roulette',
                theme: 'other',
                hasFreespins: false,
                hasLive: true,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.973,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: 10,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['live', 'roulette'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2024-04-02T10:22:22.564Z',
            },
            {
                id: 'd439f7bd-40f9-473e-843f-753b7753406e',
                slug: 'hacksaw-rusty-curly',
                identifier: 'relax:RustyAndCurly',
                featureGroup: 'relax_hacksaw_basic',
                type: 'softswiss',
                provider: 'relax',
                producer: 'hacksaw',
                title: 'Rusty & Curly',
                description: null,
                category: 'slots',
                theme: 'western',
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9629,
                hitRate: 0.3219,
                lines: null,
                ways: null,
                multiplier: 10000,
                volatility: 'medium',
                releasedAt: '2024-03-28T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2024-03-25T19:18:11.075Z',
                updatedAt: '2024-03-28T10:11:49.736Z',
            },
            {
                id: 'b6419155-409f-4634-be9b-c446373da4ab',
                slug: 'pragmatic-play-big-bass-splash',
                identifier: 'pragmaticexternal:BigBassSplash',
                featureGroup: 'pragmaticexternal_basic_lv',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Big Bass Splash',
                description: null,
                category: 'slots',
                theme: 'underwater_world',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9671,
                hitRate: null,
                lines: 10,
                ways: null,
                multiplier: 5000,
                volatility: 'high',
                releasedAt: '2022-06-23T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2023-11-24T09:05:34.403Z',
            },
            {
                id: '49270335-f5ee-4867-a4a7-157373ca43cc',
                slug: 'pragmatic-play-starlight-princess-1000',
                identifier: 'pragmaticexternal:StarlightPrincess1000',
                featureGroup: 'pragmaticexternal_basic',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Starlight Princess 1000',
                description: null,
                category: 'slots',
                theme: 'asia',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.965,
                hitRate: null,
                lines: 20,
                ways: null,
                multiplier: 15000,
                volatility: null,
                releasedAt: '2023-10-26T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-10-11T19:44:21.565Z',
                updatedAt: '2024-02-16T21:31:25.841Z',
            },
            {
                id: 'a1a9a430-5b8c-474f-904b-d37ca30ed7e3',
                slug: 'hacksaw-rip-city',
                identifier: 'relax:RIPCity96',
                featureGroup: 'relax_hacksaw_basic',
                type: 'softswiss',
                provider: 'relax',
                producer: 'hacksaw',
                title: 'RIP City',
                description: null,
                category: 'slots',
                theme: 'horrors',
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9622,
                hitRate: 0.1822,
                lines: 19,
                ways: null,
                multiplier: 12500,
                volatility: 'high',
                releasedAt: '2023-01-05T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2023-09-30T15:31:39.569Z',
            },
            {
                id: 'e311994e-e560-43ab-ac97-0cc36d29dc72',
                slug: 'pragmatic-play-ripe-rewards',
                identifier: 'pragmaticexternal:RipeRewards',
                featureGroup: 'pragmaticexternal_basic',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Ripe Rewards',
                description: null,
                category: 'slots',
                theme: 'fruits',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9602,
                hitRate: null,
                lines: 40,
                ways: null,
                multiplier: 10000,
                volatility: 'high',
                releasedAt: '2024-04-01T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2024-03-25T19:18:12.426Z',
                updatedAt: '2024-04-01T12:22:33.394Z',
            },
            {
                id: 'b89bbd6e-a5ac-4a5c-b063-8cd9730ca637',
                slug: 'pragmatic-play-the-dog-house-dog-or-alive',
                identifier: 'pragmaticexternal:TheDogHouseDogorAlive',
                featureGroup: 'pragmaticexternal_basic',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'The Dog House - Dog or Alive',
                description: null,
                category: 'slots',
                theme: 'western',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9608,
                hitRate: null,
                lines: 20,
                ways: null,
                multiplier: 10000,
                volatility: 'very-high',
                releasedAt: '2024-03-28T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2024-03-13T14:17:16.250Z',
                updatedAt: '2024-03-28T10:11:32.091Z',
            },
            {
                id: '03807447-e13d-4f19-9b10-ad8c1131b441',
                slug: 'evolution-stock-market',
                identifier: 'evolution:StockMarket',
                featureGroup: 'evolution_live',
                type: 'softswiss',
                provider: 'evolution',
                producer: 'evolution',
                title: 'Stock Market',
                description: null,
                category: 'casual',
                theme: 'other',
                hasFreespins: false,
                hasLive: true,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.99,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: '2024-03-27T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['live', 'game-show'],
                createdAt: '2024-03-25T19:18:11.889Z',
                updatedAt: '2024-03-29T17:42:06.092Z',
            },
            {
                id: 'ee0e69b6-ee82-487b-9444-e0a6a743fad4',
                slug: 'pragmatic-play-sugar-rush',
                identifier: 'pragmaticexternal:SugarRush1',
                featureGroup: 'pragmaticexternal_basic_lv',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Sugar Rush',
                description: null,
                category: 'slots',
                theme: 'sweets',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.965,
                hitRate: null,
                lines: 20,
                ways: null,
                multiplier: 5000,
                volatility: 'high',
                releasedAt: '2022-06-30T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2023-09-30T15:31:39.569Z',
            },
            {
                id: '47539971-b3a6-4e77-87f5-5af34cec0837',
                slug: 'pragmatic-play-fire-portals',
                identifier: 'pragmaticexternal:FirePortals',
                featureGroup: 'pragmaticexternal_basic',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Fire Portals',
                description: null,
                category: 'slots',
                theme: 'fantasy',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9606,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: 10000,
                volatility: 'very-high',
                releasedAt: '2024-03-21T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2024-03-11T11:20:59.762Z',
                updatedAt: '2024-03-22T09:13:41.190Z',
            },
            {
                id: 'c27c8df5-a049-4632-a911-06346ad5269a',
                slug: 'playn-go-rich-wilde-and-the-tome-of-madness',
                identifier: 'playngo:TomeofMadness',
                featureGroup: 'playngo_basic',
                type: 'softswiss',
                provider: 'playngo',
                producer: 'playngo',
                title: 'Rich Wilde and the Tome of Madness',
                description:
                    'Rich Wilde has returned! Everybody’s favourite hero is back for another adventure in the latest Play’n GO title, Rich Wilde and the Tome of Madness!Follow our intrepid explorer as he embarks on an epic quest to unlock the secrets of the sinister Cult of Cthulhu. Join him in the hunt for ancient relics and artefacts as you try to reveal the mysterious occult forces at work, and search for the legendary Book of Madness.Based on H.P. Lovecraft’s infamous fictional literary universe, the Cthulhu Mythos, this game is a 5x5 cascading grid slot, where you must match 4 or more symbols in clusters for a standard',
                category: 'slots',
                theme: 'other',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.9659,
                hitRate: null,
                lines: 1,
                ways: null,
                multiplier: 10000,
                volatility: 'very-high',
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2024-04-08T20:31:50.369Z',
            },
            {
                id: 'bdd1e35b-bb18-4c7e-9c16-baf8c3b7657c',
                slug: 'pragmatic-play-madame-destiny-megaways',
                identifier: 'pragmaticexternal:MadameDestinyMegaways1',
                featureGroup: 'pragmaticexternal_basic_lv',
                type: 'softswiss',
                provider: 'pragmaticexternal',
                producer: 'pragmaticplay',
                title: 'Madame Destiny Megaways',
                description: null,
                category: 'slots',
                theme: 'fantasy',
                hasFreespins: true,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: true,
                devices: ['desktop', 'mobile'],
                payout: 0.9656,
                hitRate: null,
                lines: null,
                ways: 200704,
                multiplier: 5000,
                volatility: 'high',
                releasedAt: '2021-01-28T00:00:00.000Z',
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['slot', 'bonus-buy'],
                createdAt: '2023-08-28T04:01:26.572Z',
                updatedAt: '2023-09-30T15:31:39.569Z',
            },
        ],
    },
    {
        section: 'originals',
        games: [
            {
                id: '1a52e2b8-ecf5-42ea-aebc-997ffbb3abc9',
                slug: 'duelbits/roulette',
                identifier: 'duelbits:roulette',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Roulette',
                description: null,
                category: 'roulette',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.93333334,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: [],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-03-12T16:58:36.798Z',
            },
            {
                id: 'd18f493b-79e4-4ad3-9ab3-555004ccb82b',
                slug: 'duelbits/dice',
                identifier: 'duelbits:dice',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Dice',
                description: null,
                category: 'casual',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.99,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: [],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-03-12T16:58:36.528Z',
            },
            {
                id: '0216e2b0-94c8-439b-bf95-322cb8f56b85',
                slug: 'duelbits/plinko',
                identifier: 'duelbits:plinko',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Plinko',
                description: null,
                category: 'casual',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.9912,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: [],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-03-12T16:58:36.546Z',
            },
            {
                id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                slug: 'duelbits/blackjack',
                identifier: 'duelbits:blackjack',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Blackjack',
                description: null,
                category: 'casual',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.9929,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['table-game', 'blackjack'],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-03-12T16:58:36.545Z',
            },
            {
                id: 'fd1e628b-91ee-4186-a233-8f2b7828fac2',
                slug: 'duelbits/crash',
                identifier: 'duelbits:crash',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Crash',
                description: null,
                category: 'casual',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.95,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: [],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-03-12T16:58:36.796Z',
            },
            {
                id: '7fc74d39-a15f-4fe6-b274-08defb2fe920',
                slug: 'duelbits/scratchcards',
                identifier: 'duelbits:scratchcards',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Scratchcards',
                description: null,
                category: 'casual',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.95,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['scratchers'],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-04-02T10:22:21.416Z',
            },
            {
                id: 'afc880ba-6528-4867-9eb1-ec7ed3d15599',
                slug: 'duelbits/mines',
                identifier: 'duelbits:mines',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Mines',
                description: null,
                category: 'casual',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.9944,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: [],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-03-29T17:42:03.900Z',
            },
            {
                id: 'c325f64c-f03c-409d-9572-d5b2b479c534',
                slug: 'duelbits/lottery',
                identifier: 'duelbits:lottery',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Lottery',
                description: null,
                category: 'lottery',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.93333334,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: [],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-03-12T16:58:36.744Z',
            },
            {
                id: '3cf40a74-0e97-41a3-8896-63e66dd0398e',
                slug: 'duelbits/duel',
                identifier: 'duelbits:duel',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Duel',
                description: null,
                category: 'casual',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.95,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: [],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-03-12T16:58:36.541Z',
            },
            {
                id: 'fdfa7299-da3c-4269-b971-b9c272c3f993',
                slug: 'duelbits/duelpoker',
                identifier: 'duelbits:duelpoker',
                featureGroup: 'duelbits_originals',
                type: 'duelbits',
                provider: 'duelbits',
                producer: 'duelbits',
                title: 'Duel Poker',
                description: null,
                category: 'poker',
                theme: null,
                hasFreespins: false,
                hasLive: false,
                hasJackpot: false,
                hasBonusBuy: false,
                devices: ['desktop', 'mobile'],
                payout: 0.96,
                hitRate: null,
                lines: null,
                ways: null,
                multiplier: null,
                volatility: null,
                releasedAt: null,
                recalledAt: null,
                recalled: false,
                status: 'enabled',
                tags: ['table-game', 'poker'],
                createdAt: '2024-02-26T19:17:03.753Z',
                updatedAt: '2024-03-12T16:58:36.795Z',
            },
        ],
    },
];

export default home;
