const promotions = [
    {
        title: 'Ultimate Fighting Jackpot - 3 BTC Jackpot & $10,000 Leaderboard',
        summary: '👊 3 Bitcoin Jackpot & a $10,000 Guaranteed Leaderboard. Exclusive to Duelbits!',
        preview: null,
        slug: 'ultimate-fighting-jackpot',
        markets: ['English (en)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play For FREE',
        cta1Link: 'https://duelbits.com/sportsbook/mma/ufc-jackpot/5fd57afa-31da-4008-868f-60c778677c70',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7tiOpOIA0vgftUB44FDz18/ab297c90660cbfac6bb085b3dcc72290/640x350-Promo__23_.jpg?fm=avif',
        },
    },
    {
        title: 'Levelling Up: More Milestones, More Rewards!',
        summary: 'Exciting enhancements to our Level-Up System await you!',
        preview: null,
        slug: 'new-levelup-rewards',
        markets: ['English (en)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)', 'Japanese (ja)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Open VIP Lounge',
        cta1Link: 'https://duelbits.com/lounge',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7oj0eYSKl9qurVsLlFoOzc/545dfa5ee967f19f44f4ebdf210a7289/640x350-duelbits-level-up-bonus-campaign.png?fm=avif',
        },
    },
    {
        title: "Johnny Walker's Jackpot Picks",
        summary: 'A Bitcoin jackpot is up for grabs this week and we also have a guaranteed $10,000 leaderboard!\n',
        preview: null,
        slug: 'johnny-walkers-jackpot-picks',
        markets: ['Portuguese (pt)', 'German (de)', 'Spanish (es)', 'French (fr)', 'Italian (it)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play Now',
        cta1Link: 'https://duelbits.com/sportsbook/mma/ufc-jackpot/5fd57afa-31da-4008-868f-60c778677c70',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/5C4ZpwVuSSbZxKPfWjMpo7/b01fce864d51ff2d5b6aace8ea4c6513/640x350-Promo__15_.jpg?fm=avif',
        },
    },
    {
        title: 'Pereira vs Hill - Free Bet Offer',
        summary: 'Place a $20 or more pre-match bet on any fight on the Alex Pereira vs Jamahal Hill card and get a $10 Free Bet to use on any sport!',
        preview: null,
        slug: 'pereira-hill-free-bet-offer',
        markets: ['English (en)', 'French (fr)', 'German (de)', 'Italian (it)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/mma',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/36t0fVwaHtVXDzLBYEkFss/da4c4ef43d42a836885f3b9c83515cee/640x350-Promo__24_.jpg?fm=avif',
        },
    },
    {
        title: 'Daily & Weekly Leaderboards',
        summary:
            'Brace yourself for an electrifying journey as we present our Leaderboards with a $200,000 monthly Prize pool up for grabs! Spin, win, repeat!',
        preview: null,
        link: '/leaderboard/daily',
        markets: ['English (en)', 'Japanese (ja)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)'],
        ctaText: null,
        ctaLink: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/2Y32ivDNvvM9gJVsqf6ZoI/5b13208d70ced50c1b6dccd55ce75847/640x350-promo-EN_1_.png?fm=avif',
        },
    },
    {
        title: 'Duelbits Blackjack - Play Up to 5 Hands Simultaneously!',
        summary:
            'Gear up for the reveal of the latest evolution of blackjack! Experience a fusion of cherished traditions from this iconic game with a touch of cutting-edge innovation.',
        preview: null,
        slug: 'duelbits-blackjack',
        markets: [
            'English (en)',
            'German (de)',
            'Spanish (es)',
            'Portuguese (pt)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play Here',
        cta1Link: 'https://duelbits.com/originals/blackjack',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/5bT8srkApsnHxXqCC3SocQ/d6a068a62d00d0d72dc5ad2e09ab1bee/640x350-duelbits-new-blackjack-promo-pack.jpg?fm=avif',
        },
    },
    {
        title: 'Win a share of $15,000!',
        summary: 'Welcome April with a month-long adventure and seize a portion of 1428 prizes worth a total of $15,000 in cash!',
        preview: null,
        slug: 'drops-frenzy',
        markets: [
            'English (en)',
            'Portuguese (pt)',
            'German (de)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/102duqKPvIbnofBt56jGYJ/e961706a20fc9cc29893c3abc5bbe208/640x350-duelbits-drop-frenzy-15k-prizepool.png?fm=avif',
        },
    },
    {
        title: 'Win a share of $1,000,000 cash every quarter',
        summary: 'Get ready to amp up the fun and dive into Mega Wheel Madness for a shot at the $1,000,000 quarterly cash Prize Pool. ',
        preview: null,
        slug: 'pragmatic-drops-and-wins-live-casino-mega-wheel-madness',
        markets: [
            'English (en)',
            'Portuguese (pt)',
            'German (de)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4Ndp6VHB0YLR0jsRZ0sM0N/9990117f8ce43a904d2de58261f4d996/640x350-promo.jpg?fm=avif',
        },
    },
    {
        title: 'IPL 2024- 180 Runs Insurance',
        summary: 'If your team scores 180 runs but go on to lose the match, then we will refund your wager as a Free Bet, up to $100!',
        preview: null,
        slug: 'ipl-insurance',
        markets: ['English (en)', 'French (fr)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/editorial/indian-premier-league',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/52WJ3t0r1xHYIdqRS8T0T5/f9e53ce85cb386523a8e7f1360192e79/640x350-Promo__12_.jpg?fm=avif',
        },
    },
    {
        title: 'New! Duelbits Instant Lottery',
        summary: 'Join the non-stop fun and take a shot at $50K, now every 5 minutes with our new Instant Lottery!',
        slug: 'instant-lottery',
        markets: [
            'English (en)',
            'German (de)',
            'Portuguese (pt)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Next draw',
        cta1Link: 'https://duelbits.com/originals/lottery',
        cta2: 'Play Here',
        cta2Link: 'https://duelbits.com/originals/lottery',
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/3FdTK2gKEWT6hPxPXJw1m4/e2d3ce9e5cefcad575a52f797c78feb0/640x400-new-brand-duelbits-lottery-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4rq291ZTr1S3l2VsAqecad/e0320095f6c14a0e223583e632204c3d/640x350-duelbits-new-instant-lottery.jpg?fm=avif',
        },
    },
    {
        title: 'Fantasy Sports Now On Duelbits',
        summary: 'Put your knowledge to the test in our very own Fantasy Sports. Take part in our FREE to Play Duels game to win Real Prizes! ',
        preview: null,
        slug: 'fantasy-sports-terms',
        markets: ['English (en)', 'Portuguese (pt)', 'German (de)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play Now',
        cta1Link: 'https://duelbits.com/sportsbook/fantasy-sports',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/qo1Km8qQOBtJRxhsvlk8D/09fc33e38efdd4ca0dcd7c82eaea710e/640x350-promo__98_.jpg?fm=avif',
        },
    },
    {
        title: 'Win a share of $2,000,000 each month',
        summary: 'Play on your favorite Pragmatic games for a share of $25,480,000! It only takes a spin to win, 7 days a week.',
        preview: null,
        slug: 'pragmatic-drops-and-wins-slots-2024-may',
        markets: [
            'English (en)',
            'Portuguese (pt)',
            'German (de)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/1im9pJ1TvDoZN7dmV5Ab8H/5425553090dccb0cebb86447c2bb35f6/640x350-promo.png?fm=avif',
        },
    },
    {
        title: '$10,000,000 Spinoleague Tournaments',
        summary: 'Step into the glitz of Sapphire Season - $2.5 million awaits, just for you!',
        preview: null,
        slug: 'spinoleague-sapphire-season',
        markets: [
            'English (en)',
            'German (de)',
            'Portuguese (pt)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/5QTxCImbVGi70qDJODUPWz/c1821f6d20b81011f90bb9f8350072a5/640x350-promo.jpg?fm=avif',
        },
    },
    {
        title: 'New & Improved Multi Boost',
        summary:
            'Win up to an EXTRA 200% with Duelbits brand new and improved Multi Boost!󠀠󠀠󠀠󠀠󠀠󠀠󠀠󠀠󠀠󠀠ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ    ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤAll you need to do is place a multiple bet with at least 2 selections where each leg has 1.20 odds or higher, it could not be any simpler.',
        preview: null,
        slug: 'new-multi-boost',
        markets: ['English (en)', 'Spanish (es)', 'German (de)', 'Japanese (ja)', 'Portuguese (pt)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7kDgPX16chmfZ5hhmTXUKD/1d96eee45ab36397ef038cad812c5d46/640x350-Promo__2_.jpg?fm=avif',
        },
    },
    {
        title: 'NBA - 120 Is Plenty',
        summary:
            "Every team is a winner, even the one that isn't! Thanks to our exclusive NBA offer, if your team scores 120 points, you’ll win no matter what.",
        preview: null,
        slug: 'nba-120-is-plenty',
        markets: ['English (en)', 'Portuguese (pt)', 'Spanish (es)', 'German (de)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/basketball',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4ZUwg1CIU6Jo5j08LiYdhZ/0423c3350742088d0346c012be662fd1/640x350-Promo__39_.jpg?fm=avif',
        },
    },
    {
        title: 'Premier League - Lead At Half-Time Insurance',
        summary: 'If your selection leads at half-time in any Premier League match but goes on to lose or draw, then we will refund your bet, up to $100.',
        slug: 'premier-league',
        markets: ['English (en)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/soccer',
        cta2: null,
        cta2Link: null,
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/6ZrVLLSSXYjadq4s8r7w7M/1588c2a876e8b7fbc56d5bbb283dbc25/640x400-Promo-thumb__3_.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/3qqUvVnimvZGk2r3wAMPVe/eb0d0b064011592a2cf9673dc69c5b58/640x350-Promo__14_.jpg?fm=avif',
        },
    },
    {
        title: 'NHL Overtime Insurance',
        summary:
            'Place a pre-match single bet on a team in the Winner (incl. overtime and penalties) market on any NHL match & if your team loses in overtime, then we will refund your wager up to $100 as a Free Bet token!',
        preview: null,
        slug: 'nhl-new-overtime-insurance',
        markets: ['English (en)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/ice-hockey',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7mgr19GTo8gSsZubBHEoxB/0a9a649a8ab7cde9fdc4bf7f57c8caa5/640x350-Promo__19_.jpg?fm=avif',
        },
    },
    {
        title: null,
        summary: 'Wager through your deposit 5x to receive your original deposit back as a free bet.',
        preview: null,
        slug: 'sportsbook-welcome-offer',
        markets: ['English (en)', 'German (de)', 'Spanish (es)', 'Portuguese (pt)', 'Japanese (ja)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Claim Your Bonus Now!',
        cta1Link: 'https://duelbits.com/?modal=Auth&type=register',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4TtL5ABACWlCXiwewUzS97/841737916728826a09b45c83016464ea/640x350-Promo-EN__2_.jpg?fm=avif',
        },
    },
];

export default promotions;
