const promotionsCasino = [
    {
        title: 'Celebrate the return of Mines',
        summary: 'Our explosive Mines game is back! Find gems and avoid the mines for up to $1,000,000 payout.',
        slug: 'mines-return',
        markets: [
            'English (en)',
            'German (de)',
            'Portuguese (pt)',
            'Spanish (es)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
            'Japanese (ja)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: '💎 Play Now 💣',
        cta1Link: 'https://duelbits.com/mines',
        cta2: '💎 Play Now 💣',
        cta2Link: 'https://duelbits.com/mines',
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/6x6l6kkbHCuh0eVCZ5HXUh/e77c6eaccd71be8ab78d03aee670e119/640x400-Promo-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/1DGqULq7s5NTgR0L0taaES/878fa45d0b4deaec7e3839eedf3b36b7/640x350-promo.jpg?fm=avif',
        },
    },
    {
        title: 'Daily & Weekly Leaderboards',
        summary:
            'Brace yourself for an electrifying journey as we present our Leaderboards with a $200,000 monthly Prize pool up for grabs! Spin, win, repeat!',
        preview: null,
        link: '/leaderboard/daily',
        markets: ['English (en)', 'Japanese (ja)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)'],
        ctaText: null,
        ctaLink: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/2Y32ivDNvvM9gJVsqf6ZoI/5b13208d70ced50c1b6dccd55ce75847/640x350-promo-EN_1_.png?fm=avif',
        },
    },
    {
        title: 'Levelling Up: More Milestones, More Rewards!',
        summary: 'Exciting enhancements to our Level-Up System await you!',
        preview: null,
        slug: 'new-levelup-rewards',
        markets: [
            'English (en)',
            'German (de)',
            'Portuguese (pt)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Open VIP Lounge',
        cta1Link: 'https://duelbits.com/lounge',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7oj0eYSKl9qurVsLlFoOzc/545dfa5ee967f19f44f4ebdf210a7289/640x350-duelbits-level-up-bonus-campaign.png?fm=avif',
        },
    },
    {
        title: 'Duelbits Blackjack - Play Up to 5 Hands Simultaneously!',
        summary:
            'Gear up for the reveal of the latest evolution of blackjack! Experience a fusion of cherished traditions from this iconic game with a touch of cutting-edge innovation.',
        preview: null,
        slug: 'duelbits-blackjack',
        markets: [
            'English (en)',
            'German (de)',
            'Spanish (es)',
            'Portuguese (pt)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play Here',
        cta1Link: 'https://duelbits.com/originals/blackjack',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/5bT8srkApsnHxXqCC3SocQ/d6a068a62d00d0d72dc5ad2e09ab1bee/640x350-duelbits-new-blackjack-promo-pack.jpg?fm=avif',
        },
    },
    {
        title: 'Ultimate Fighting Jackpot - 1 BTC Jackpot & $2,000 Leaderboard',
        summary: '👊 A Bitcoin Jackpot & a $2,000 Guaranteed Leaderboard. Exclusive to Duelbits!',
        preview: null,
        slug: 'ultimate-fighting-jackpot',
        markets: [
            'English (en)',
            'Spanish (es)',
            'French (fr)',
            'German (de)',
            'Italian (it)',
            'Portuguese (pt)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
            'Japanese (ja)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play For FREE',
        cta1Link: 'https://duelbits.com/sportsbook/mma/ufc-jackpot/5fd57afa-31da-4008-868f-60c778677c70',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4zxC6UtKVnt3KkuCC6hKwq/59679a30e01e4ab84db3db4befbb939b/640x350-Promo__27_.jpg?fm=avif',
        },
    },
    {
        title: 'New! Duelbits Instant Lottery',
        summary: 'Join the non-stop fun and take a shot at $50K, now every 5 minutes with our new Instant Lottery!',
        slug: 'instant-lottery',
        markets: [
            'English (en)',
            'German (de)',
            'Portuguese (pt)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Next draw',
        cta1Link: 'https://duelbits.com/originals/lottery',
        cta2: 'Play Here',
        cta2Link: 'https://duelbits.com/originals/lottery',
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/3FdTK2gKEWT6hPxPXJw1m4/e2d3ce9e5cefcad575a52f797c78feb0/640x400-new-brand-duelbits-lottery-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4rq291ZTr1S3l2VsAqecad/e0320095f6c14a0e223583e632204c3d/640x350-duelbits-new-instant-lottery.jpg?fm=avif',
        },
    },
    {
        title: 'Duelbits Scratchcards - Buy, scratch, win!',
        summary: "Do you like scratchcards? Then you'll love our brand-new scratchcard games!",
        preview: null,
        slug: 'scratch',
        markets: [
            'German (de)',
            'Portuguese (pt)',
            'Spanish (es)',
            'English (en)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play Now',
        cta1Link: 'https://duelbits.com/originals/scratchcards',
        cta2: 'Play Now',
        cta2Link: 'https://duelbits.com/originals/scratchcards',
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7Fa74enjUGrjPtZfkCCSSc/5fa770077533cc2bd57af25633efdc79/640x350-promo_2_.jpg?fm=avif',
        },
    },
    {
        title: 'Win a share of $15,000!',
        summary: 'Welcome April with a month-long adventure and seize a portion of 1428 prizes worth a total of $15,000 in cash!',
        preview: null,
        slug: 'drops-frenzy',
        markets: [
            'English (en)',
            'Portuguese (pt)',
            'German (de)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/102duqKPvIbnofBt56jGYJ/e961706a20fc9cc29893c3abc5bbe208/640x350-duelbits-drop-frenzy-15k-prizepool.png?fm=avif',
        },
    },
    {
        title: '$10,000,000 Spinoleague Tournaments',
        summary: 'Step into the glitz of Sapphire Season - $2.5 million awaits, just for you!',
        preview: null,
        slug: 'spinoleague-sapphire-season',
        markets: [
            'English (en)',
            'German (de)',
            'Portuguese (pt)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/5QTxCImbVGi70qDJODUPWz/c1821f6d20b81011f90bb9f8350072a5/640x350-promo.jpg?fm=avif',
        },
    },
    {
        title: 'Win a share of $2,000,000 each month',
        summary: 'Play on your favorite Pragmatic games for a share of $25,480,000! It only takes a spin to win, 7 days a week.',
        preview: null,
        slug: 'pragmatic-drops-and-wins-slots-2024-may',
        markets: [
            'English (en)',
            'Portuguese (pt)',
            'German (de)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/1im9pJ1TvDoZN7dmV5Ab8H/5425553090dccb0cebb86447c2bb35f6/640x350-promo.png?fm=avif',
        },
    },
    {
        title: 'Win a share of $1,000,000 cash every quarter',
        summary: 'Get ready to amp up the fun and dive into Mega Wheel Madness for a shot at the $1,000,000 quarterly cash Prize Pool. ',
        preview: null,
        slug: 'pragmatic-drops-and-wins-live-casino-mega-wheel-madness',
        markets: [
            'English (en)',
            'Portuguese (pt)',
            'German (de)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4Ndp6VHB0YLR0jsRZ0sM0N/9990117f8ce43a904d2de58261f4d996/640x350-promo.jpg?fm=avif',
        },
    },
    {
        title: 'Lucky Day: Win 10% Bonus ',
        summary: "On your Lucky Day, you'll receive 10% of your scratchcard winnings as a gift from us!",
        slug: 'scratchcards-lucky-day',
        markets: [
            'English (en)',
            'German (de)',
            'Portuguese (pt)',
            'Spanish (es)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
            'Japanese (ja)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Opt in here',
        cta1Link: 'https://duelbits.com/my-rewards',
        cta2: null,
        cta2Link: null,
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/3Zque6K77x447huKYuDSI8/20812f0df2ef5fe06083f0481b87327f/640x400-Promo-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/16k3edChb5wj1eAoSl3pGH/d4c4f249200270b49acff7bc0f5d7517/640x350-Promo.jpg?fm=avif',
        },
    },
    {
        title: 'Crypto Prices',
        summary: 'Follow the latest cryptocurrency prices with our new live tracking tool!',
        preview: null,
        link: '/crypto',
        markets: ['English (en)'],
        ctaText: null,
        ctaLink: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/2ObyxuclG1d0o9MsaEHGX8/21832b23412308256b47c6abd3dcbbf9/640x350-promo.png?fm=avif',
        },
    },
    {
        title: 'New Payment Method: Shiba Inu',
        summary:
            'The perfect embodiment of a meme coin: the name of the cryptocurrency is the breed of the dog of the Doge meme. And the logo is a visual representation of said canine. ',
        slug: 'shiba',
        markets: ['English (en)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Deposit Now',
        cta1Link: 'https://duelbits.com/promotions/shiba?modal=Cashier&tab=deposit',
        cta2: null,
        cta2Link: null,
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/5DbZVNJ95AqW0wKK7raQTa/4493616813326dc4870536ecc8a62bf7/640x400-shiba-inu-duelbits-new-payment-method-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/5kk3Y04UhwlZ3hnC5Bhktq/aa976bdf693f61e2fa5019b0d7f9e955/640x350-shiba-inu-duelbits-new-payment-method.png?fm=avif',
        },
    },
    {
        title: 'Duel Poker',
        summary:
            'Duel Poker is a unique community-based game where every 15 seconds a round of poker is being played. This round of poker is played between two automated players.',
        slug: 'duel-poker',
        markets: ['English (en)', 'Spanish (es)', 'German (de)', 'Portuguese (pt)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play here',
        cta1Link: 'https://duelbits.com/originals/duel-poker',
        cta2: 'Play here',
        cta2Link: 'https://duelbits.com/originals/duel-poker',
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/700jTvYFLwNCJA1teEh2dd/6bb71ea47db0f555714dcc31fd58f365/640x400-Promo-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/53xhzwlNaGOVYiNvryUDrv/aa05b4cc302db9ae030a6c06b45c9f82/640x350-Promo.png?fm=avif',
        },
    },
    {
        title: 'Try the New & Unique NFT Feature',
        summary:
            "Receive NFTs from Victoria's story & craft low-rare NFT into more valuable NFT, and even create Onyx Victoria and get 100% of the Holders Treasury, making up 0.1% of all the players’ in-game bets paid monthly.",
        slug: 'victoria-nft',
        markets: ['English (en)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play Here',
        cta1Link: 'https://duelbits.com/slots/truelab:VictoriaWildWest',
        cta2: null,
        cta2Link: null,
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/1PMWqmyigFpueiaeI0pc3j/16dd5031ef3acc6046b860d44a378c37/640x400-Promo-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/31PaSFhbEfd9OIA8nfD091/69201cac0330bfc74d30eeab6e8f71f5/640x350-Promo.jpg?fm=avif',
        },
    },
    {
        title: 'New Payment Method: TRON',
        summary: 'We now accept TRON as a payment method. Use your preferred e-wallet, cryptocurrency, bank card or CS:GO items to make deposits.',
        slug: 'tron',
        markets: ['English (en)', 'German (de)', 'Spanish (es)', 'Portuguese (pt)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Deposit Now',
        cta1Link: 'https://duelbits.com/promotions/tron?modal=Cashier&tab=deposit',
        cta2: null,
        cta2Link: null,
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/3HOwD1HRR8mqjEwiqDgLhW/1535c2f3679e57d9c984fd6345c69c62/640x400-tron-duelbits-new-payment-method-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/qWN2otrKh7elhtBv0QECX/0b18479dc2f49cb1a6b9babc6a0993ca/640x350-tron-duelbits-new-payment-method.png?fm=avif',
        },
    },
    {
        title: 'New Payment Method: ApeCoin',
        summary: 'We are now accepting ApeCoin as a new payment method. ApeCoin is an ERC-20 governance and utility token used within the APE ecosystem.',
        slug: 'apecoin',
        markets: ['English (en)', 'Portuguese (pt)', 'German (de)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Deposit Now',
        cta1Link: 'https://duelbits.com/promotions/apecoin?modal=Cashier&tab=deposit',
        cta2: null,
        cta2Link: null,
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7tpSSluGdcs0yKznIePLZc/328660df281bf0292e8e254e3278fbf7/640x400-apecoin-duelbits-new-payment-method-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4RjaRZ2vpl81TjYAttFE2A/68dc8333459e19bb1fbf97ec1ef338d9/640x350-apecoin-duelbits-new-payment-method.png?fm=avif',
        },
    },
    {
        title: 'Play Our Plinko Game with Unique Extreme Modes',
        summary: 'The popular Plinko game has arrived with exciting Game Modes and insane multipliers! Win up to $1,000,000.',
        slug: 'plinko',
        markets: ['English (en)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play Plinko',
        cta1Link: 'https://duelbits.com/plinko',
        cta2: 'Play Plinko Now!',
        cta2Link: 'https://duelbits.com/plinko',
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/76wOoQBAxvcljJ36xSRqzi/71bf035154df4efa3f7fa2842b4cae5b/640x400-Promo-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/77WhJQCsYtt6iZnOWt2juV/752415e22e8cbd450e003aba728842df/640x350-Promo.png?fm=avif',
        },
    },
    {
        title: 'Play Our Unique Dice Game',
        summary: 'The popular dice game has now arrived at Duelbits with additional unique betting options. Choose your odds and try it today!',
        slug: 'dice',
        markets: ['English (en)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play Dice',
        cta1Link: 'https://duelbits.com/dice',
        cta2: null,
        cta2Link: null,
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7hdFu6u5egImfoZnYFEUeS/8d404bfa2c46056e58545e48f2f01f61/640x400-Promo-thumb.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/268X0rwLhkjsNfc1tQVTaw/e7265b633192b8e16d154553cd240d97/640x350-Promo.jpg?fm=avif',
        },
    },
];

export default promotionsCasino;
