// GET https://sportsapi.pick500.net:60009/api/Pregame/getTopLeagues?lang=en&siteid=0

const topLeagues = {
    SubCategs: [
        {
            SubCateg: {
                Id: 1,
                CategId: 0,
                Name: 'Football',
                ViewOrder: 1,
            },
            Items: [
                {
                    Id: 0,
                    SubCategId: 0,
                    Name: 'La Liga',
                    Icon: 'https://cdnwallet2.modulesports.com/uploads/leagues/LA LIGA NUOVO LOGO_1700747530726..png',
                    Value: '1,252,1048',
                    Par1: '1',
                    Par2: 'Spain',
                    FoundInRole: 0,
                    FoundInAccounId: 0,
                },
                {
                    Id: 0,
                    SubCategId: 0,
                    Name: 'First Division',
                    Icon: 'https://cdnwallet.pick777.net/uploads/leagues/FirstDivision_1705774052666..png',
                    Value: '1,632,3962',
                    Par1: '1',
                    Par2: 'Cyprus',
                    FoundInRole: 0,
                    FoundInAccounId: 0,
                },
                {
                    Id: 0,
                    SubCategId: 0,
                    Name: 'Ligue 1',
                    Icon: 'https://cdnwallet2.modulesports.com/uploads/leagues/1045_1700234770969..png',
                    Value: '1,250,1045',
                    Par1: '1',
                    Par2: 'France',
                    FoundInRole: 0,
                    FoundInAccounId: 0,
                },
                {
                    Id: 0,
                    SubCategId: 0,
                    Name: 'Bundesliga',
                    Icon: 'https://cdnwallet2.modulesports.com/uploads/leagues/1026_1700234593247..png',
                    Value: '1,231,1026',
                    Par1: '1',
                    Par2: 'Germany',
                    FoundInRole: 0,
                    FoundInAccounId: 0,
                },
                {
                    Id: 0,
                    SubCategId: 0,
                    Name: 'Premier League',
                    Icon: 'https://cdnwallet2.modulesports.com/uploads/leagues/premieleague_1700406585691..png',
                    Value: '1,236,1116',
                    Par1: '1',
                    Par2: 'England',
                    FoundInRole: 0,
                    FoundInAccounId: 0,
                },
                {
                    Id: 0,
                    SubCategId: 0,
                    Name: 'Serie A',
                    Icon: 'https://cdnwallet2.modulesports.com/uploads/leagues/Serie A _1700237919669..png',
                    Value: '1,430,3024',
                    Par1: '2',
                    Par2: 'Italy',
                    FoundInRole: 0,
                    FoundInAccounId: 0,
                },
                {
                    Id: 0,
                    SubCategId: 0,
                    Name: 'Super League 1',
                    Icon: 'https://cdnwallet2.modulesports.com/uploads/leagues/greece super league_1703160069958..png',
                    Value: '1,500,4513',
                    Par1: '3',
                    Par2: 'Greece',
                    FoundInRole: 0,
                    FoundInAccounId: 0,
                },
            ],
        },
    ],
};

export default topLeagues;
