const promotionsSport = [
    {
        title: 'Ultimate Fighting Jackpot - 1 BTC Jackpot & $2,000 Leaderboard',
        summary: '👊 A Bitcoin Jackpot & a $2,000 Guaranteed Leaderboard. Exclusive to Duelbits!',
        preview: null,
        slug: 'ultimate-fighting-jackpot',
        markets: [
            'English (en)',
            'Spanish (es)',
            'French (fr)',
            'German (de)',
            'Italian (it)',
            'Portuguese (pt)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
            'Japanese (ja)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play For FREE',
        cta1Link: 'https://duelbits.com/sportsbook/mma/ufc-jackpot/5fd57afa-31da-4008-868f-60c778677c70',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4zxC6UtKVnt3KkuCC6hKwq/59679a30e01e4ab84db3db4befbb939b/640x350-Promo__27_.jpg?fm=avif',
        },
    },
    {
        title: 'El Clásico - Free Bet Offer',
        summary: 'Get a $10 Free Bet to use on any sport when you place a $20 or more pre-match bet on the Real Madrid vs Barcelona game.',
        preview: null,
        slug: 'el-clasico-free-bet',
        markets: ['English (en)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/soccer/match/41893537-Real-Madrid-vs-FC-Barcelona',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/5qXObxww6rG41GMxL9cXM5/70646a5c7c7044c994289bf9c9d67753/640x350-Promo__36_.jpg?fm=avif',
        },
    },
    {
        title: 'IPL 2024- 180 Runs Insurance',
        summary: 'If your team scores 180 runs but go on to lose the match, then we will refund your wager as a Free Bet, up to $100!',
        preview: null,
        slug: 'ipl-insurance',
        markets: ['English (en)', 'French (fr)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/editorial/indian-premier-league',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/52WJ3t0r1xHYIdqRS8T0T5/f9e53ce85cb386523a8e7f1360192e79/640x350-Promo__12_.jpg?fm=avif',
        },
    },
    {
        title: 'New & Improved Multi Boost',
        summary:
            'Win up to an EXTRA 200% with Duelbits brand new and improved Multi Boost!󠀠󠀠󠀠󠀠󠀠󠀠󠀠󠀠󠀠󠀠ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ    ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤAll you need to do is place a multiple bet with at least 2 selections where each leg has 1.20 odds or higher, it could not be any simpler.',
        preview: null,
        slug: 'new-multi-boost',
        markets: ['English (en)', 'Spanish (es)', 'German (de)', 'Japanese (ja)', 'Portuguese (pt)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: null,
        cta1Link: null,
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7kDgPX16chmfZ5hhmTXUKD/1d96eee45ab36397ef038cad812c5d46/640x350-Promo__2_.jpg?fm=avif',
        },
    },
    {
        title: 'Levelling Up: More Milestones, More Rewards!',
        summary: 'Exciting enhancements to our Level-Up System await you!',
        preview: null,
        slug: 'new-levelup-rewards',
        markets: [
            'English (en)',
            'German (de)',
            'Portuguese (pt)',
            'Spanish (es)',
            'Japanese (ja)',
            'French (fr)',
            'Italian (it)',
            'Chinese - Traditional (zh-Hant)',
            'Chinese - Simplified (zh-Hans)',
        ],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Open VIP Lounge',
        cta1Link: 'https://duelbits.com/lounge',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7oj0eYSKl9qurVsLlFoOzc/545dfa5ee967f19f44f4ebdf210a7289/640x350-duelbits-level-up-bonus-campaign.png?fm=avif',
        },
    },
    {
        title: 'Fantasy Sports Now On Duelbits',
        summary: 'Put your knowledge to the test in our very own Fantasy Sports. Take part in our FREE to Play Duels game to win Real Prizes! ',
        preview: null,
        slug: 'fantasy-sports-terms',
        markets: ['English (en)', 'Portuguese (pt)', 'German (de)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Play Now',
        cta1Link: 'https://duelbits.com/sportsbook/fantasy-sports',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/qo1Km8qQOBtJRxhsvlk8D/09fc33e38efdd4ca0dcd7c82eaea710e/640x350-promo__98_.jpg?fm=avif',
        },
    },
    {
        title: 'NBA - 120 Is Plenty',
        summary:
            "Every team is a winner, even the one that isn't! Thanks to our exclusive NBA offer, if your team scores 120 points, you’ll win no matter what.",
        preview: null,
        slug: 'nba-120-is-plenty',
        markets: ['English (en)', 'Portuguese (pt)', 'Spanish (es)', 'German (de)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/basketball',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/4ZUwg1CIU6Jo5j08LiYdhZ/0423c3350742088d0346c012be662fd1/640x350-Promo__39_.jpg?fm=avif',
        },
    },
    {
        title: 'Daily & Weekly Leaderboards',
        summary:
            'Brace yourself for an electrifying journey as we present our Leaderboards with a $200,000 monthly Prize pool up for grabs! Spin, win, repeat!',
        preview: null,
        link: '/leaderboard/daily',
        markets: ['English (en)', 'Japanese (ja)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)'],
        ctaText: null,
        ctaLink: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/2Y32ivDNvvM9gJVsqf6ZoI/5b13208d70ced50c1b6dccd55ce75847/640x350-promo-EN_1_.png?fm=avif',
        },
    },
    {
        title: 'Premier League - Lead At Half-Time Insurance',
        summary: 'If your selection leads at half-time in any Premier League match but goes on to lose or draw, then we will refund your bet, up to $100.',
        slug: 'premier-league',
        markets: ['English (en)', 'German (de)', 'Portuguese (pt)', 'Spanish (es)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/soccer',
        cta2: null,
        cta2Link: null,
        preview: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/6ZrVLLSSXYjadq4s8r7w7M/1588c2a876e8b7fbc56d5bbb283dbc25/640x400-Promo-thumb__3_.jpg?fm=avif',
        },
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/3qqUvVnimvZGk2r3wAMPVe/eb0d0b064011592a2cf9673dc69c5b58/640x350-Promo__14_.jpg?fm=avif',
        },
    },
    {
        title: 'NHL Overtime Insurance',
        summary:
            'Place a pre-match single bet on a team in the Winner (incl. overtime and penalties) market on any NHL match & if your team loses in overtime, then we will refund your wager up to $100 as a Free Bet token!',
        preview: null,
        slug: 'nhl-new-overtime-insurance',
        markets: ['English (en)'],
        start: null,
        betIntent: null,
        wasOdd: null,
        nowOdd: null,
        cta1: 'Bet Now',
        cta1Link: 'https://duelbits.com/sportsbook/ice-hockey',
        cta2: null,
        cta2Link: null,
        banner: {
            url: 'https://images.ctfassets.net/im9yudtc78wp/7mgr19GTo8gSsZubBHEoxB/0a9a649a8ab7cde9fdc4bf7f57c8caa5/640x350-Promo__19_.jpg?fm=avif',
        },
    },
];

export default promotionsSport;
