// const config = {
//     VITE_CASINO_BASE: 'https://casinoapi.storetube.gr:61020/api',
//     VITE_WALLET_API_BASE: 'https://storetube.gr:61009/api',
//     VITE_SPORTS_API_BASE: 'https://storetube.gr:60009/api',
//     VITE_SPORTS_LOGOS: 'https://cdnsports.pick777.net/assets',
//     VITE_CASINO_LOBBY: 'https://casinom.storetube.gr',
//     VITE_CASINO_LIVE_LOBBY: 'https://casinom.storetube.gr',
//     VITE_BETS_API: 'https://storetube.gr:60019/api',
//     VITE_SITE_ID: 45,
//     VITE_HOME_URL: 'https://betovix.storetube.gr',

//     VITE_WALLET_STORETUBE: 'https://storetube.gr:61009/api',
//     VITE_STORETUBE: 'https://storetube.gr:60019/api',
//     VITE_CASINO_STORETUBE_BASE: 'https://casinoapi.storetube.gr:61020/api',

//     VITE_GAMIFICATION_STORETUBE: 'https://gamificationapi.storetube.gr:61113/api',
// };

const config = {
    VITE_CASINO_BASE: SETTINGS.VITE_CASINO_BASE,
    VITE_WALLET_API_BASE: SETTINGS.VITE_WALLET_API_BASE,
    VITE_SPORTS_API_BASE: SETTINGS.VITE_SPORTS_API_BASE,
    VITE_SPORTS_LOGOS: SETTINGS.VITE_SPORTS_LOGOS,
    VITE_CASINO_LOBBY: SETTINGS.VITE_CASINO_LOBBY,
    VITE_CASINO_LIVE_LOBBY: SETTINGS.VITE_CASINO_BASE,
    VITE_BETS_API: SETTINGS.VITE_BETS_API,
    VITE_SITE_ID: SETTINGS.VITE_SITE_ID,
    VITE_HOME_URL: SETTINGS.VITE_HOME_URL,

    VITE_WALLET_STORETUBE: SETTINGS.VITE_WALLET_STORETUBE,
    VITE_STORETUBE: SETTINGS.VITE_STORETUBE,
    VITE_CASINO_STORETUBE_BASE: SETTINGS.VITE_CASINO_STORETUBE_BASE,

    VITE_GAMIFICATION_STORETUBE: SETTINGS.VITE_GAMIFICATION_STORETUBE,
    
    VITE_GOOGLE_CLIENT_ID: SETTINGS.VITE_GOOGLE_CLIENT_ID,
    VITE_UPLOAD: SETTINGS.VITE_UPLOAD,
    VITE_SITE_NAME: "",
};
export default config;
